"""
Field browser — mappa statica dei campi disponibili per ogni tipo sorgente.
Ogni entry: {field_path, label, tipo (string/integer/decimal/date/boolean/currency), group?}
"""

FIELD_MAP = {
    'DATORE': [
        # Diretti
        {'field_path': 'codice_fiscale', 'label': 'Codice Fiscale', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'nome_cognome', 'label': 'Nome e Cognome', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'indirizzo', 'label': 'Indirizzo', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'comune', 'label': 'Comune', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'email', 'label': 'Email', 'tipo': 'string', 'group': 'Contatti'},
        {'field_path': 'telefono', 'label': 'Telefono', 'tipo': 'string', 'group': 'Contatti'},
        {'field_path': 'pin_inps', 'label': 'PIN INPS', 'tipo': 'string', 'group': 'Dati Fiscali'},
        {'field_path': 'invio_digitale_documenti', 'label': 'Invio Digitale', 'tipo': 'boolean', 'group': 'Impostazioni'},
        {'field_path': 'note_datore', 'label': 'Note', 'tipo': 'string', 'group': 'Anagrafica'},
        # Computed
        {'field_path': 'n_progetti', 'label': 'N. Progetti', 'tipo': 'integer', 'group': 'Statistiche'},
        {'field_path': 'n_contratti_attivi', 'label': 'N. Contratti Attivi', 'tipo': 'integer', 'group': 'Statistiche'},
    ],

    'LAVORATORE': [
        {'field_path': 'codice_fiscale', 'label': 'Codice Fiscale', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'nome_cognome', 'label': 'Nome e Cognome', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'indirizzo', 'label': 'Indirizzo', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'comune', 'label': 'Comune', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'email', 'label': 'Email', 'tipo': 'string', 'group': 'Contatti'},
        {'field_path': 'telefono', 'label': 'Telefono', 'tipo': 'string', 'group': 'Contatti'},
        {'field_path': 'ferie_pregresse', 'label': 'Ferie Pregresse', 'tipo': 'decimal', 'group': 'Dati Contrattuali'},
        {'field_path': 'scatti_anzianita_maturati', 'label': 'Scatti Maturati', 'tipo': 'integer', 'group': 'Dati Contrattuali'},
        {'field_path': 'note_lavoratore', 'label': 'Note', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'n_contratti_attivi', 'label': 'N. Contratti Attivi', 'tipo': 'integer', 'group': 'Statistiche'},
    ],

    'BENEFICIARIO': [
        {'field_path': 'codice_fiscale', 'label': 'Codice Fiscale', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'nome_cognome', 'label': 'Nome e Cognome', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'indirizzo', 'label': 'Indirizzo', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'comune', 'label': 'Comune', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'email', 'label': 'Email', 'tipo': 'string', 'group': 'Contatti'},
        {'field_path': 'telefono', 'label': 'Telefono', 'tipo': 'string', 'group': 'Contatti'},
        {'field_path': 'note_beneficiario', 'label': 'Note', 'tipo': 'string', 'group': 'Anagrafica'},
        {'field_path': 'n_progetti', 'label': 'N. Progetti', 'tipo': 'integer', 'group': 'Statistiche'},
    ],

    'CONTRATTO': [
        # Relazioni
        {'field_path': 'datore.nome_cognome', 'label': 'Datore (Nome)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.codice_fiscale', 'label': 'Datore (CF)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.comune', 'label': 'Datore (Comune)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.indirizzo', 'label': 'Datore (Indirizzo)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.telefono', 'label': 'Datore (Telefono)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.email', 'label': 'Datore (Email)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.note_datore', 'label': 'Datore (Note)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'lavoratore.nome_cognome', 'label': 'Lavoratore (Nome)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.codice_fiscale', 'label': 'Lavoratore (CF)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.comune', 'label': 'Lavoratore (Comune)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.indirizzo', 'label': 'Lavoratore (Indirizzo)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.telefono', 'label': 'Lavoratore (Telefono)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.email', 'label': 'Lavoratore (Email)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.note_lavoratore', 'label': 'Lavoratore (Note)', 'tipo': 'string', 'group': 'Lavoratore'},
        # Diretti
        {'field_path': 'stato', 'label': 'Stato', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'codice_rapporto_inps', 'label': 'Cod. Rapporto INPS', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'data_assunzione', 'label': 'Data Assunzione', 'tipo': 'date', 'group': 'Contratto'},
        {'field_path': 'data_inizio_tfr', 'label': 'Data Inizio TFR', 'tipo': 'date', 'group': 'Contratto'},
        {'field_path': 'tipo_contratto', 'label': 'Tipo Contratto', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'note_post_it', 'label': 'Note / Post-it', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'giorni_malattia_usati_anno', 'label': 'Giorni Malattia Usati', 'tipo': 'integer', 'group': 'Contratto'},
        {'field_path': 'busta_template.codice', 'label': 'Template Busta (Codice)', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'busta_template.oggetto_titolo', 'label': 'Template Busta (Titolo)', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'applica_scatti', 'label': 'Applica Scatti', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'modalita_tfr', 'label': 'Modalità TFR', 'tipo': 'string', 'group': 'Opzioni'},
        {'field_path': 'paga_tfr', 'label': 'TFR (deprecato)', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'paga_13ma', 'label': '13\u00aa Mensilit\u00e0', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'paga_festivi', 'label': 'Festivi', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'paga_ferie', 'label': 'Ferie', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'usa_retribuzione_sostituzione', 'label': 'Retrib. Sostituzione', 'tipo': 'boolean', 'group': 'Opzioni'},
        # Dettagli indicatori
        {'field_path': 'is_convivente', 'label': 'Lavoratore Convivente', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_certificazione_qualita', 'label': 'Certificazione Qualità', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_piu_persone_non_conv', 'label': 'Più Persone (Non Conv)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_minori_non_conv', 'label': 'Minori < 6a (Non Conv)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_piu_persone_qualita', 'label': 'Più Persone + Qualità', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_minori_qualita', 'label': 'Minori + Qualità', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_funzione_conviventi', 'label': 'Indennità Funzione', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_assistenza_piu_persone_ft', 'label': 'Più Persone (Conv FT)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_assistenza_piu_persone_pt', 'label': 'Più Persone (Conv PT)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_minori_6_anni_ft', 'label': 'Minori < 6a (Conv FT)', 'tipo': 'boolean', 'group': 'Indicatori'},
        # Notturno
        {'field_path': 'applica_notturno_assistenza', 'label': 'Notturno Assistenza', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'applica_notturno_presenza', 'label': 'Notturno Presenza', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'applica_notturno_base', 'label': 'Notturno Base', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'applica_notturno_20', 'label': 'Notturno 20%', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_tfr', 'label': 'Notturno TFR', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_13ma', 'label': 'Notturno 13\u00aa', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_festivi', 'label': 'Notturno Festivi', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_ferie', 'label': 'Notturno Ferie', 'tipo': 'boolean', 'group': 'Notturno'},
        # Conviventi
        {'field_path': 'ind_conviventi_ft_54h', 'label': 'Conviventi FT (54h)', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'ind_conviventi_pt_30h', 'label': 'Conviventi PT (30h)', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'paga_pranzo', 'label': 'Conv. Pranzo', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'paga_cena', 'label': 'Conv. Cena', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'paga_alloggio', 'label': 'Conv. Alloggio', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_funzione_mensile', 'label': 'Usa Ind. Funzione Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_minori_6_mensile_ft', 'label': 'Usa Ind. Minori <6 FT Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_minori_6_mensile_pt', 'label': 'Usa Ind. Minori <6 PT Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_piu_assistiti_mensile', 'label': 'Usa Ind. Più Assistiti Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_cert_qualita_mensile', 'label': 'Usa Ind. Cert. Qualità Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'ore_mav_custom', 'label': 'Mod. Ore PagoPA', 'tipo': 'integer', 'group': 'Ore'},
        {'field_path': 'ore_calcolate', 'label': 'Ore Calcolate', 'tipo': 'decimal', 'group': 'Ore'},
        # FK -> ParametriCCNL
        {'field_path': 'parametri_minimi.descrizione_corta', 'label': 'Parametri (Descrizione)', 'tipo': 'string', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.livello.codice', 'label': 'Livello', 'tipo': 'string', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.paga_base', 'label': 'Paga Base', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.tfr_orario', 'label': 'TFR Orario', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.tredicesima_oraria', 'label': '13\u00aa Oraria', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.descrizione_lunga', 'label': 'Parametri (Desc. Lunga)', 'tipo': 'string', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.anno', 'label': 'Anno CCNL', 'tipo': 'integer', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.retribuzione_sostituzione', 'label': 'Retrib. Sostituzione', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.festivi_orari', 'label': 'Festivi Orari', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ferie_orarie', 'label': 'Ferie Orarie', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_cert_qualita', 'label': 'Ind. Cert. Qualità', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_assistenza_piu_persone_non_conv', 'label': 'Ind. Più Persone (Non Conv)', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_minori_6_anni_non_conv', 'label': 'Ind. Minori <6a (Non Conv)', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_piu_persone_qualita', 'label': 'Ind. Più Persone + Qualità', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_minori_qualita', 'label': 'Ind. Minori + Qualità', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_assistenza_piu_persone_ft', 'label': 'Ind. Più Persone (Conv FT)', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_assistenza_piu_persone_pt', 'label': 'Ind. Più Persone (Conv PT)', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_minori_6_anni_ft', 'label': 'Ind. Minori <6a (Conv FT)', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_notturno_assistenza', 'label': 'Ind. Notturno Assistenza', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_notturno_presenza', 'label': 'Ind. Notturno Presenza', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_notturno_base', 'label': 'Ind. Notturno Base', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_notturno_20', 'label': 'Ind. Notturno 20%', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.notturno_tfr', 'label': 'Notturno TFR Orario', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.notturno_13ma', 'label': 'Notturno 13ª Oraria', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.notturno_festivi', 'label': 'Notturno Festivi Orari', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.notturno_ferie', 'label': 'Notturno Ferie Orarie', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_funzione_conviventi', 'label': 'Ind. Funzione Conviventi', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.conviventi_ft_54h', 'label': 'Conviventi FT Max 54h', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.conviventi_pt_30h', 'label': 'Conviventi PT Max 30h', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.convivenza_pranzo', 'label': 'Conv. Pranzo Orario', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.convivenza_cena', 'label': 'Conv. Cena Orario', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.convivenza_alloggio', 'label': 'Conv. Alloggio Orario', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.minimo_mensile_ft', 'label': 'Minimo Mensile FT', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.minimo_mensile_pt', 'label': 'Minimo Mensile PT', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_funzione_mensile', 'label': 'Ind. Funzione Mensile', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_minori_6_mensile_ft', 'label': 'Ind. Minori <6 FT Mensile', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_minori_6_mensile_pt', 'label': 'Ind. Minori <6 PT Mensile', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_piu_assistiti_mensile', 'label': 'Ind. Più Assistiti Mensile', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ind_cert_qualita_mensile', 'label': 'Ind. Cert. Qualità Mensile', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.fonte_url', 'label': 'Fonte URL', 'tipo': 'string', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.livello.colore', 'label': 'Livello (Colore)', 'tipo': 'string', 'group': 'Parametri'},
        # FK -> TabellaCasse
        {'field_path': 'ente_bilaterale.codice', 'label': 'Ente (Codice)', 'tipo': 'string', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.descrizione', 'label': 'Ente (Descrizione)', 'tipo': 'string', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.totale', 'label': 'Ente (Totale)', 'tipo': 'currency', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.quota_datore', 'label': 'Ente (Quota Datore)', 'tipo': 'currency', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.quota_lavoratore', 'label': 'Ente (Quota Lavoratore)', 'tipo': 'currency', 'group': 'Ente'},
        # FK aggiuntive Datore
        {'field_path': 'datore.pin_inps', 'label': 'Datore (PIN INPS)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.invio_digitale_documenti', 'label': 'Datore (Invio Digitale)', 'tipo': 'boolean', 'group': 'Datore'},
        # FK aggiuntive Lavoratore
        {'field_path': 'lavoratore.ferie_pregresse', 'label': 'Lavoratore (Ferie Pregresse)', 'tipo': 'decimal', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.scatti_anzianita_maturati', 'label': 'Lavoratore (Scatti Maturati)', 'tipo': 'integer', 'group': 'Lavoratore'},
        # Properties
        {'field_path': 'budget_di_partenza', 'label': 'Budget Mensile', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'budget_annuale', 'label': 'Budget Annuale (x12)', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'ore_mensili_calcolate', 'label': 'Ore Mensili', 'tipo': 'decimal', 'group': 'Ore'},
        {'field_path': 'ore_settimanali_calcolate', 'label': 'Ore Settimanali', 'tipo': 'decimal', 'group': 'Ore'},
        {'field_path': 'paga_oraria_totale', 'label': 'Paga Oraria Totale', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'quota_convivenza_mensile', 'label': 'Quota Convivenza', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'trattenuta_ratei_accantonati', 'label': 'Ratei Accantonati', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'totale_tfr_accantonato_cumulativo', 'label': 'TFR Acc. Cumulativo', 'tipo': 'currency', 'group': 'Calcoli'},
        # Pseudo campi INPS/PagoPA (come da lista PagoPA)
        {'field_path': 'ore_inps', 'label': 'Ore INPS (ceil)', 'tipo': 'integer', 'group': 'PagoPA'},
        {'field_path': 'paga_oraria_inps', 'label': 'Paga Oraria INPS', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'cassa_orario', 'label': 'Cassa Oraria', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'aliquota_inps_orario', 'label': 'Aliquota INPS Oraria', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'soglia_contributi_superata', 'label': 'Soglia Contributi (>24.9h)', 'tipo': 'boolean', 'group': 'PagoPA'},
        {'field_path': 'ore_trim', 'label': 'Ore Trimestrali (INPS x3)', 'tipo': 'integer', 'group': 'PagoPA'},
        {'field_path': 'imp_cassa_trim', 'label': 'Imp. Cassa Trimestrale', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'stima_contrib_trim', 'label': 'Stima Contrib. Trimestrale', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'contrib_totali', 'label': 'Contributi Totali Trim.', 'tipo': 'currency', 'group': 'PagoPA'},
        # M2M — progetti collegati
        {'field_path': 'progetti_lista', 'label': 'Progetti (lista)', 'tipo': 'string', 'group': 'Progetti'},
    ],

    'PROGETTO_REGIONALE': [
        {'field_path': 'beneficiario.nome_cognome', 'label': 'Beneficiario', 'tipo': 'string', 'group': 'Beneficiario'},
        {'field_path': 'beneficiario.codice_fiscale', 'label': 'Beneficiario (CF)', 'tipo': 'string', 'group': 'Beneficiario'},
        {'field_path': 'beneficiario.comune', 'label': 'Comune', 'tipo': 'string', 'group': 'Beneficiario'},
        {'field_path': 'tipo.nome', 'label': 'Tipo (Nome)', 'tipo': 'string', 'group': 'Tipo'},
        {'field_path': 'tipo.colore', 'label': 'Tipo (Colore)', 'tipo': 'string', 'group': 'Tipo'},
        {'field_path': 'tipo.descrizione', 'label': 'Tipo (Descrizione)', 'tipo': 'string', 'group': 'Tipo'},
        {'field_path': 'beneficiario.email', 'label': 'Beneficiario (Email)', 'tipo': 'string', 'group': 'Beneficiario'},
        {'field_path': 'beneficiario.telefono', 'label': 'Beneficiario (Tel.)', 'tipo': 'string', 'group': 'Beneficiario'},
        {'field_path': 'beneficiario.note_beneficiario', 'label': 'Beneficiario (Note)', 'tipo': 'string', 'group': 'Beneficiario'},
        {'field_path': 'beneficiario.indirizzo', 'label': 'Beneficiario (Indirizzo)', 'tipo': 'string', 'group': 'Beneficiario'},
        {'field_path': 'data_inizio', 'label': 'Data Inizio', 'tipo': 'date', 'group': 'Date'},
        {'field_path': 'data_fine', 'label': 'Data Fine', 'tipo': 'date', 'group': 'Date'},
        {'field_path': 'budget_annuale', 'label': 'Budget Annuale', 'tipo': 'currency', 'group': 'Economico'},
        {'field_path': 'budget_mensile', 'label': 'Budget Mensile', 'tipo': 'currency', 'group': 'Economico'},
        {'field_path': 'mesi', 'label': 'Mesi', 'tipo': 'integer', 'group': 'Economico'},
    ],

    'PAGOPA_INPS': [
        # Datore
        {'field_path': 'datore.nome_cognome', 'label': 'Datore (Nome)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.codice_fiscale', 'label': 'Datore (CF)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.comune', 'label': 'Datore (Comune)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.indirizzo', 'label': 'Datore (Indirizzo)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.telefono', 'label': 'Datore (Telefono)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.email', 'label': 'Datore (Email)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.pin_inps', 'label': 'Datore (PIN INPS)', 'tipo': 'string', 'group': 'Datore'},
        {'field_path': 'datore.invio_digitale_documenti', 'label': 'Datore (Invio Digitale)', 'tipo': 'boolean', 'group': 'Datore'},
        {'field_path': 'datore.note_datore', 'label': 'Datore (Note)', 'tipo': 'string', 'group': 'Datore'},
        # Lavoratore
        {'field_path': 'lavoratore.nome_cognome', 'label': 'Lavoratore (Nome)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.codice_fiscale', 'label': 'Lavoratore (CF)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.comune', 'label': 'Lavoratore (Comune)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.indirizzo', 'label': 'Lavoratore (Indirizzo)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.telefono', 'label': 'Lavoratore (Telefono)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.email', 'label': 'Lavoratore (Email)', 'tipo': 'string', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.ferie_pregresse', 'label': 'Lavoratore (Ferie Pregresse)', 'tipo': 'decimal', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.scatti_anzianita_maturati', 'label': 'Lavoratore (Scatti Maturati)', 'tipo': 'integer', 'group': 'Lavoratore'},
        {'field_path': 'lavoratore.note_lavoratore', 'label': 'Lavoratore (Note)', 'tipo': 'string', 'group': 'Lavoratore'},
        # Contratto / INPS
        {'field_path': 'codice_rapporto_inps', 'label': 'Cod. Rapp. INPS', 'tipo': 'string', 'group': 'INPS'},
        {'field_path': 'stato', 'label': 'Stato Contratto', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'data_assunzione', 'label': 'Data Assunzione', 'tipo': 'date', 'group': 'Contratto'},
        {'field_path': 'data_inizio_tfr', 'label': 'Data Inizio TFR', 'tipo': 'date', 'group': 'Contratto'},
        {'field_path': 'tipo_contratto', 'label': 'Tipo Contratto', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'note_post_it', 'label': 'Note / Post-it', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'giorni_malattia_usati_anno', 'label': 'Giorni Malattia Usati', 'tipo': 'integer', 'group': 'Contratto'},
        {'field_path': 'busta_template.codice', 'label': 'Template Busta (Codice)', 'tipo': 'string', 'group': 'Contratto'},
        {'field_path': 'busta_template.oggetto_titolo', 'label': 'Template Busta (Titolo)', 'tipo': 'string', 'group': 'Contratto'},
        # Opzioni
        {'field_path': 'applica_scatti', 'label': 'Applica Scatti', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'modalita_tfr', 'label': 'Modalit\u00e0 TFR', 'tipo': 'string', 'group': 'Opzioni'},
        {'field_path': 'paga_tfr', 'label': 'TFR (deprecato)', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'paga_13ma', 'label': '13\u00aa Mensilit\u00e0', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'paga_festivi', 'label': 'Festivi', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'paga_ferie', 'label': 'Ferie', 'tipo': 'boolean', 'group': 'Opzioni'},
        {'field_path': 'usa_retribuzione_sostituzione', 'label': 'Retrib. Sostituzione', 'tipo': 'boolean', 'group': 'Opzioni'},
        # Indicatori
        {'field_path': 'is_convivente', 'label': 'Lavoratore Convivente', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_certificazione_qualita', 'label': 'Certificazione Qualit\u00e0', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_piu_persone_non_conv', 'label': 'Pi\u00f9 Persone (Non Conv)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_minori_non_conv', 'label': 'Minori < 6a (Non Conv)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_funzione_conviventi', 'label': 'Indennit\u00e0 Funzione', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_assistenza_piu_persone_ft', 'label': 'Pi\u00f9 Persone (Conv FT)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_assistenza_piu_persone_pt', 'label': 'Pi\u00f9 Persone (Conv PT)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_minori_6_anni_ft', 'label': 'Minori < 6a (Conv FT)', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_piu_persone_qualita', 'label': 'Pi\u00f9 Persone + Qualit\u00e0', 'tipo': 'boolean', 'group': 'Indicatori'},
        {'field_path': 'ind_minori_qualita', 'label': 'Minori + Qualit\u00e0', 'tipo': 'boolean', 'group': 'Indicatori'},
        # Notturno
        {'field_path': 'applica_notturno_assistenza', 'label': 'Notturno Assistenza', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'applica_notturno_presenza', 'label': 'Notturno Presenza', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'applica_notturno_base', 'label': 'Notturno Base', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'applica_notturno_20', 'label': 'Notturno 20%', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_tfr', 'label': 'Notturno TFR', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_13ma', 'label': 'Notturno 13\u00aa', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_festivi', 'label': 'Notturno Festivi', 'tipo': 'boolean', 'group': 'Notturno'},
        {'field_path': 'paga_notturno_ferie', 'label': 'Notturno Ferie', 'tipo': 'boolean', 'group': 'Notturno'},
        # Conviventi
        {'field_path': 'ind_conviventi_ft_54h', 'label': 'Conviventi FT (54h)', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'ind_conviventi_pt_30h', 'label': 'Conviventi PT (30h)', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'paga_pranzo', 'label': 'Conv. Pranzo', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'paga_cena', 'label': 'Conv. Cena', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'paga_alloggio', 'label': 'Conv. Alloggio', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_funzione_mensile', 'label': 'Usa Ind. Funzione Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_minori_6_mensile_ft', 'label': 'Usa Ind. Minori <6 FT Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_minori_6_mensile_pt', 'label': 'Usa Ind. Minori <6 PT Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_piu_assistiti_mensile', 'label': 'Usa Ind. Pi\u00f9 Assistiti Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        {'field_path': 'usa_ind_cert_qualita_mensile', 'label': 'Usa Ind. Cert. Qualit\u00e0 Mensile', 'tipo': 'boolean', 'group': 'Conviventi'},
        # Ore
        {'field_path': 'ore_calcolate', 'label': 'Ore Calcolate', 'tipo': 'decimal', 'group': 'Ore'},
        {'field_path': 'ore_mensili_calcolate', 'label': 'Ore Mensili', 'tipo': 'decimal', 'group': 'Ore'},
        {'field_path': 'ore_settimanali_calcolate', 'label': 'Ore Settimanali', 'tipo': 'decimal', 'group': 'Ore'},
        {'field_path': 'ore_mav_custom', 'label': 'Mod. Ore PagoPA', 'tipo': 'integer', 'group': 'Ore'},
        {'field_path': 'ore_inps', 'label': 'Ore INPS (ceil mensili)', 'tipo': 'integer', 'group': 'INPS'},
        {'field_path': 'ore_trim', 'label': 'Ore Trimestrali (INPS x 3)', 'tipo': 'integer', 'group': 'INPS'},
        # Parametri
        {'field_path': 'parametri_minimi.livello.codice', 'label': 'Livello', 'tipo': 'string', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.descrizione_corta', 'label': 'Parametri (Descrizione)', 'tipo': 'string', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.descrizione_lunga', 'label': 'Parametri (Desc. Lunga)', 'tipo': 'string', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.paga_base', 'label': 'Paga Base', 'tipo': 'currency', 'group': 'Retribuzione'},
        {'field_path': 'parametri_minimi.tfr_orario', 'label': 'TFR Orario', 'tipo': 'currency', 'group': 'Retribuzione'},
        {'field_path': 'parametri_minimi.tredicesima_oraria', 'label': '13\u00aa Oraria', 'tipo': 'currency', 'group': 'Retribuzione'},
        {'field_path': 'parametri_minimi.festivi_orari', 'label': 'Festivi Orari', 'tipo': 'currency', 'group': 'Parametri'},
        {'field_path': 'parametri_minimi.ferie_orarie', 'label': 'Ferie Orarie', 'tipo': 'currency', 'group': 'Parametri'},
        # Ente
        {'field_path': 'ente_bilaterale.codice', 'label': 'Cod. Cassa', 'tipo': 'string', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.descrizione', 'label': 'Cassa (Descrizione)', 'tipo': 'string', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.totale', 'label': 'Cassa (Totale)', 'tipo': 'currency', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.quota_datore', 'label': 'Cassa (Quota Datore)', 'tipo': 'currency', 'group': 'Ente'},
        {'field_path': 'ente_bilaterale.quota_lavoratore', 'label': 'Cassa (Quota Lavoratore)', 'tipo': 'currency', 'group': 'Ente'},
        # Calcoli
        {'field_path': 'budget_di_partenza', 'label': 'Budget Mensile', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'budget_annuale', 'label': 'Budget Annuale (x12)', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'paga_oraria_totale', 'label': 'Paga Oraria Totale', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'quota_convivenza_mensile', 'label': 'Quota Convivenza', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'trattenuta_ratei_accantonati', 'label': 'Ratei Accantonati', 'tipo': 'currency', 'group': 'Calcoli'},
        {'field_path': 'totale_tfr_accantonato_cumulativo', 'label': 'TFR Acc. Cumulativo', 'tipo': 'currency', 'group': 'Calcoli'},
        # PagoPA
        {'field_path': 'paga_oraria_inps', 'label': 'Paga Oraria INPS (troncata)', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'cassa_orario', 'label': 'Cassa Oraria', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'aliquota_inps_orario', 'label': 'Aliquota INPS Oraria', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'imp_cassa_trim', 'label': 'Imp. Cassa Trim.', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'stima_contrib_trim', 'label': 'Stima Contrib. Trim.', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'contrib_totali', 'label': 'Contributi Totali', 'tipo': 'currency', 'group': 'PagoPA'},
        {'field_path': 'soglia_contributi_superata', 'label': 'Soglia (>24.9h)', 'tipo': 'boolean', 'group': 'PagoPA'},
        # Progetti
        {'field_path': 'progetti_lista', 'label': 'Progetti (lista)', 'tipo': 'string', 'group': 'Progetti'},
    ],
}

TIPO_GROUP_MAP = {
    'string': 'string',
    'integer': 'integer',
    'decimal': 'decimal',
    'date': 'date',
    'boolean': 'boolean',
    'currency': 'currency',
}
