# Generated by Django 6.0.5 on 2026-05-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('modello_coinvolto', models.CharField(max_length=50)),
                ('azione', models.CharField(max_length=255)),
                ('dettagli', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Registro di Audit (Scatola Nera)',
                'ordering': ['-data_ora'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('codice_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='CODICE FISCALE')),
                ('nome_cognome', models.CharField(max_length=100, verbose_name=' COGNOME E NOME')),
                ('indirizzo', models.CharField(blank=True, max_length=200, verbose_name='INDIRIZZO')),
                ('comune', models.CharField(blank=True, max_length=100, verbose_name='COMUNE DI RESIDENZA')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='INDIRIZZO EMAIL')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='NUMERO TELEFONO O CELLULARE')),
                ('note_beneficiario', models.TextField(blank=True, null=True, verbose_name='NOTE BENEFICIARIO')),
            ],
            options={
                'verbose_name_plural': 'Anagrafica: Beneficiari',
                'ordering': ['nome_cognome'],
            },
        ),
        migrations.CreateModel(
            name='ContrattoLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('ATTIVO', 'Attivo'), ('CESSATO', 'Cessato')], default='ATTIVO', max_length=10)),
                ('codice_rapporto_inps', models.CharField(blank=True, max_length=50)),
                ('data_assunzione', models.DateField()),
                ('data_inizio_tfr', models.DateField(blank=True, null=True)),
                ('tipo_contratto', models.CharField(choices=[('INDETERMINATO', 'Indeterminato'), ('DETERMINATO', 'Determinato')], default='INDETERMINATO', max_length=15)),
                ('applica_scatti', models.BooleanField(default=True, verbose_name='Applica scatti')),
                ('paga_tfr', models.BooleanField(default=True, verbose_name='TFR')),
                ('paga_13ma', models.BooleanField(default=True, verbose_name='TREDICESIMA')),
                ('paga_festivi', models.BooleanField(default=True, verbose_name='FESTIVI')),
                ('paga_ferie', models.BooleanField(default=True, verbose_name='FERIE')),
                ('ore_mav_custom', models.IntegerField(blank=True, null=True, verbose_name='MODIFICA ORE PAGOPA')),
                ('ind_certificazione_qualita', models.BooleanField(default=False, verbose_name='CERTIFICAZIONE DI QUALITÀ')),
                ('ind_piu_persone_non_conv', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE (NON CONV)')),
                ('ind_minori_non_conv', models.BooleanField(default=False, verbose_name='IND. MINORI < 6 ANNI (NON CONV)')),
                ('ind_piu_persone_qualita', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE + QUALITÀ')),
                ('ind_minori_qualita', models.BooleanField(default=False, verbose_name='IND. MINORI + QUALITÀ')),
                ('ind_assistenza_piu_persone_ft', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE (CONV FT)')),
                ('ind_assistenza_piu_persone_pt', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE (CONV PT)')),
                ('ind_minori_6_anni_ft', models.BooleanField(default=False, verbose_name='IND. MINORI < 6 ANNI (CONV FT)')),
                ('applica_notturno_assistenza', models.BooleanField(default=False, verbose_name='NOTTURNO ASSISTENZA (20-08)')),
                ('applica_notturno_presenza', models.BooleanField(default=False, verbose_name='NOTTURNO PRESENZA (21-08)')),
                ('applica_notturno_base', models.BooleanField(default=False, verbose_name='NOTTURNO PAGA BASE')),
                ('applica_notturno_20', models.BooleanField(default=False, verbose_name='NOTTURNO PAGA BASE (20%)')),
                ('paga_notturno_tfr', models.BooleanField(default=False, verbose_name='NOTTURNO TFR')),
                ('paga_notturno_13ma', models.BooleanField(default=False, verbose_name='NOTTURNO TREDICESIMA')),
                ('paga_notturno_festivi', models.BooleanField(default=False, verbose_name='NOTTURNO FESTIVI')),
                ('paga_notturno_ferie', models.BooleanField(default=False, verbose_name='NOTTURNO FERIE')),
                ('ind_funzione_conviventi', models.BooleanField(default=False, verbose_name='INDENNITÀ FUNZIONE')),
                ('ind_conviventi_ft_54h', models.BooleanField(default=False, verbose_name='CONVIVENTI FT (54H)')),
                ('ind_conviventi_pt_30h', models.BooleanField(default=False, verbose_name='CONVIVENTI PT (30H)')),
                ('is_convivente', models.BooleanField(default=False, verbose_name='Lavoratore Convivente (Sì/No)')),
                ('paga_pranzo', models.BooleanField(default=False, verbose_name='CONVIVENZA PRANZO')),
                ('paga_cena', models.BooleanField(default=False, verbose_name='CONVIVENZA CENA')),
                ('paga_alloggio', models.BooleanField(default=False, verbose_name='CONVIVENZA ALLOGGIO')),
                ('note_post_it', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': '6. Anagrafica: Contratti',
                'ordering': ['datore__nome_cognome', 'lavoratore__nome_cognome'],
            },
        ),
        migrations.CreateModel(
            name='DatoreLavoro',
            fields=[
                ('codice_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='CODICE FISCALE')),
                ('nome_cognome', models.CharField(max_length=100, verbose_name=' COGNOME E NOME')),
                ('indirizzo', models.CharField(blank=True, max_length=200, verbose_name='INDIRIZZO')),
                ('comune', models.CharField(blank=True, max_length=100, verbose_name='COMUNE DI RESIDENZA')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='INDIRIZZO EMAIL')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='NUMERO TELEFONO O CELLULARE')),
                ('pin_inps', models.CharField(blank=True, max_length=50, verbose_name=' PIN INPS - PIN TESSERA SANITARIA O CIE')),
                ('invio_digitale_documenti', models.BooleanField(default=True, verbose_name='INVIO DIGITALE DEI DOCUMENTI?')),
                ('note_datore', models.TextField(blank=True, null=True, verbose_name='NOTE DATORE DI LAVORO')),
            ],
            options={
                'verbose_name_plural': 'Anagrafica: Datori',
                'ordering': ['nome_cognome'],
            },
        ),
        migrations.CreateModel(
            name='GestoreBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('tipo_backup', models.CharField(choices=[('COMPLETO', '1. Completo'), ('ANAGRAFICHE', '2. Solo Anagrafiche'), ('CONTRATTI', '3. Solo Contratti e Progetti'), ('PARAMETRI', '4. Solo Tabelle Parametriche')], default='COMPLETO', max_length=20)),
                ('note_opzionali', models.CharField(blank=True, max_length=200)),
                ('file_json', models.FileField(blank=True, null=True, upload_to='backups_json/')),
            ],
            options={
                'verbose_name_plural': '💾 Gestione Backup',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Lavoratore',
            fields=[
                ('codice_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='CODICE FISCALE')),
                ('nome_cognome', models.CharField(max_length=100, verbose_name=' COGNOME E NOME')),
                ('indirizzo', models.CharField(blank=True, max_length=200, verbose_name='INDIRIZZO')),
                ('comune', models.CharField(blank=True, max_length=100, verbose_name='COMUNE DI RESIDENZA')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='INDIRIZZO EMAIL')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='NUMERO TELEFONO O CELLULARE')),
                ('ferie_pregresse', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='FERIE PREGRESSE')),
                ('scatti_anzianita_maturati', models.IntegerField(default=0, verbose_name="SCATTI ANZIANITA'")),
                ('note_lavoratore', models.TextField(blank=True, null=True, verbose_name='NOTE LAVORATORE')),
            ],
            options={
                'verbose_name_plural': 'Anagrafica: Lavoratori',
                'ordering': ['nome_cognome'],
            },
        ),
        migrations.CreateModel(
            name='OpzioniSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_programma', models.CharField(default='Paghe COLF & Badanti 2026', max_length=100, verbose_name='NOME PROGRAMMA')),
                ('versione_programma', models.CharField(default='1.1', max_length=20, verbose_name='VERSIONE')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='loghi_studio/', verbose_name='LOGO PROGRAMMA')),
                ('exe_lettore_pdf', models.CharField(blank=True, max_length=255, verbose_name='LINK AL LETTORE PDF')),
                ('path_locale_pdf', models.CharField(blank=True, max_length=255, verbose_name='PATH LOCALE PDF')),
                ('exe_posta', models.CharField(blank=True, max_length=255, verbose_name='LINK AL PROGRAMMA DI POSTA')),
                ('path_locale_posta', models.CharField(blank=True, max_length=255, verbose_name='PATH LOCALE POSTA')),
                ('cartella_backup', models.CharField(blank=True, max_length=255, verbose_name='CARTELLA BACKUP')),
                ('cartella_documenti', models.CharField(blank=True, max_length=255, verbose_name='CARTELLA DOCUMENTI')),
                ('link_inps_mav', models.URLField(blank=True, default='https://serviziweb2.inps.it/PagamentiBollettiniLD/accessoUtente.do', max_length=255, verbose_name='LINK AL SITO INPS PER I PAGOPA')),
                ('link_inps_iscrizione', models.URLField(blank=True, default='https://www.inps.it/it/it/dettaglio-scheda.it.schede-servizio-strumento.schede-servizi.formalizzare-l-assunzione-di-un-lavoratore-domestico.html', max_length=255, verbose_name='LINK AL SITO INPS PER IL LAVORO DOMESTICO')),
                ('link_python', models.URLField(blank=True, default='https://www.python.org', max_length=255, verbose_name='LINK A PYTHON')),
                ('link_chromedriver', models.URLField(blank=True, default='https://googlechromelabs.github.io/chrome-for-testing/', max_length=255, verbose_name='LINK A CHROMEDRIVER')),
                ('soglia_ore_contributi', models.DecimalField(decimal_places=2, default=24.9, max_digits=5, verbose_name='SOGLIA ORE CONTRIBUTI, PER VERIFICA SUPERAMENTO')),
                ('rateo_ferie_mensile', models.DecimalField(decimal_places=2, default=2.16, max_digits=5, verbose_name='RATEO FERIE MENSILI')),
                ('mesi_annuali_std', models.IntegerField(default=12, verbose_name='MESI ANNUALI STANDARD')),
                ('giorni_mensili_std', models.IntegerField(default=26, verbose_name='GIORNI MENSILI STANDARD')),
                ('settimane_annuali_std', models.IntegerField(default=52, verbose_name='SETTIMANE ANNUALI STANDARD')),
                ('anno_gestione', models.IntegerField(default=2026, verbose_name='ANNO DI GESTIONE')),
                ('dati_studio', models.TextField(blank=True, verbose_name='DATI STUDIO')),
                ('telefono_studio', models.CharField(blank=True, max_length=100, verbose_name='TELEFONO STUDIO')),
                ('email_studio', models.EmailField(blank=True, max_length=254, verbose_name='MAIL STUDIO')),
                ('alert_contributi', models.TextField(blank=True, verbose_name='ALERT CONTRIBUTI')),
                ('note_footer_mail', models.TextField(blank=True, verbose_name='NOTE FOOTER MAIL')),
                ('firma_email', models.TextField(blank=True, verbose_name='FIRMA MAIL')),
            ],
            options={
                'verbose_name': 'Opzioni Software',
                'verbose_name_plural': '0. Opzioni Software',
            },
        ),
        migrations.CreateModel(
            name='ParametriCCNL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.CharField(max_length=5, verbose_name='LIVELLO')),
                ('descrizione_corta', models.CharField(blank=True, max_length=100, verbose_name='DESCRIZIONE')),
                ('descrizione_lunga', models.TextField(blank=True, verbose_name='DESCRIZIONE LUNGA')),
                ('anno', models.IntegerField(default=2026, verbose_name='ANNO')),
                ('paga_base', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='RETRIBUZIONE BASE')),
                ('retribuzione_sostituzione', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='RETRIB. SOSTITUZIONE')),
                ('tfr_orario', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='TFR')),
                ('tredicesima_oraria', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='TREDICESIMA')),
                ('festivi_orari', models.DecimalField(decimal_places=4, default=0.3333, max_digits=10, verbose_name='FESTIVI')),
                ('ferie_orarie', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='FERIE')),
                ('ind_cert_qualita', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='CERTIFICAZIONE DI QUALITÀ')),
                ('ind_assistenza_piu_persone_non_conv', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='IND. PIÙ PERSONE (NON CONV)')),
                ('ind_minori_6_anni_non_conv', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='IND. MINORI < 6 ANNI (NON CONV)')),
                ('ind_piu_persone_qualita', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='IND. PIÙ PERSONE + QUALITÀ')),
                ('ind_minori_qualita', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='IND. MINORI + QUALITÀ')),
                ('ind_assistenza_piu_persone_ft', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='IND. PIÙ PERSONE (CONV FT)')),
                ('ind_assistenza_piu_persone_pt', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='IND. PIÙ PERSONE (CONV PT)')),
                ('ind_minori_6_anni_ft', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='IND. MINORI < 6 ANNI (CONV FT)')),
                ('ind_notturno_assistenza', models.DecimalField(decimal_places=4, default=811.09, max_digits=10, verbose_name='NOTTURNO ASSISTENZA (20-08)')),
                ('ind_notturno_presenza', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='NOTTURNO PRESENZA (21-08)')),
                ('ind_notturno_base', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='NOTTURNO PAGA BASE')),
                ('ind_notturno_20', models.DecimalField(decimal_places=4, default=1.2, max_digits=10, verbose_name='NOTTURNO PAGA BASE (20%)')),
                ('notturno_tfr', models.DecimalField(decimal_places=4, default=0.3208, max_digits=10, verbose_name='NOTTURNO TFR')),
                ('notturno_13ma', models.DecimalField(decimal_places=4, default=0.3094, max_digits=10, verbose_name='NOTTURNO TREDICESIMA')),
                ('notturno_festivi', models.DecimalField(decimal_places=4, default=0.3333, max_digits=10, verbose_name='NOTTURNO FESTIVI')),
                ('notturno_ferie', models.DecimalField(decimal_places=4, default=0.3094, max_digits=10, verbose_name='NOTTURNO FERIE')),
                ('ind_funzione_conviventi', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='INDENNITÀ FUNZIONE')),
                ('conviventi_ft_54h', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='CONVIVENTI FT (MAX 54H) LORDI')),
                ('conviventi_pt_30h', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='CONVIVENTI PT (MAX 30H)')),
                ('convivenza_pranzo', models.DecimalField(decimal_places=4, default=2.33, max_digits=10, verbose_name='CONVIVENZA PRANZO')),
                ('convivenza_cena', models.DecimalField(decimal_places=4, default=2.33, max_digits=10, verbose_name='CONVIVENZA CENA')),
                ('convivenza_alloggio', models.DecimalField(decimal_places=4, default=2.0, max_digits=10, verbose_name='CONVIVENZA ALLOGGIO')),
            ],
        ),
        migrations.CreateModel(
            name='TabellaCasse',
            fields=[
                ('codice', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='CODICE')),
                ('descrizione', models.CharField(max_length=100, verbose_name='DESCRIZIONE')),
                ('quota_datore', models.DecimalField(decimal_places=4, default=0.04, max_digits=10, verbose_name='QUOTA DATORE')),
                ('quota_lavoratore', models.DecimalField(decimal_places=4, default=0.02, max_digits=10, verbose_name='QUOTA LAVORATORE')),
                ('totale', models.DecimalField(decimal_places=4, default=0.06, max_digits=10, verbose_name='TOTALE')),
            ],
            options={
                'verbose_name_plural': '1. Tabelle Casse (F2/E1)',
            },
        ),
        migrations.CreateModel(
            name='TabellaContributiINPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, verbose_name='DESCRIZIONE')),
                ('quota_datore', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='QUOTA DATORE')),
                ('quota_lavoratore', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='QUOTA LAVORATORE')),
                ('totale', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='TOTALE')),
            ],
            options={
                'verbose_name_plural': '4. Tabelle Contributi INPS',
            },
        ),
        migrations.CreateModel(
            name='TabellaMalattia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzianita', models.CharField(max_length=100, verbose_name="ANZIANITA'")),
                ('giorni_durata', models.IntegerField(verbose_name='GIORNI DURATA')),
                ('conservazione_posto', models.IntegerField(verbose_name='GIORNI CONSERVAZIONE POSTO')),
            ],
            options={
                'verbose_name_plural': '5. Tabelle Malattia',
            },
        ),
        migrations.CreateModel(
            name='TabellaScattiAnzianita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.CharField(choices=[('A', 'A'), ('AS', 'AS'), ('B', 'B'), ('BS', 'BS'), ('C', 'C'), ('CS', 'CS'), ('D', 'D'), ('DS', 'DS')], max_length=2, verbose_name='LIVELLO')),
                ('valore_scatto', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='VALORE SCATTO')),
            ],
            options={
                'verbose_name_plural': '2. Tabelle Scatti Anzianità',
            },
        ),
        migrations.CreateModel(
            name='TestoPreimpostato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MAIL', 'Modello Email'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune')], default='MAIL', max_length=20, verbose_name='TIPO')),
                ('codice', models.CharField(max_length=50, unique=True, verbose_name='CODICE')),
                ('oggetto_titolo', models.CharField(max_length=200, verbose_name='OGGETTO')),
                ('corpo_testo', models.TextField(verbose_name='CORPO TESTO')),
                ('note_interne', models.TextField(blank=True, verbose_name='NOTE INTERNE')),
            ],
            options={
                'verbose_name_plural': '0. Testi Preimpostati',
            },
        ),
        migrations.CreateModel(
            name='TipoProgettoRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='NOME')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='DESCRIZIONE')),
            ],
            options={
                'verbose_name_plural': 'Tipi di Progetto Regionale',
            },
        ),
        migrations.CreateModel(
            name='ContrattoAttivo',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Contratti Attivi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paghe.contrattolavoro',),
        ),
        migrations.CreateModel(
            name='ContrattoCessato',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Contratti Cessati',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paghe.contrattolavoro',),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='datore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paghe.datorelavoro'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='lavoratore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paghe.lavoratore'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='parametri_minimi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paghe.parametriccnl'),
        ),
        migrations.CreateModel(
            name='ProgettoRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField(blank=True, null=True, verbose_name='DATA INIZIO')),
                ('data_fine', models.DateField(blank=True, null=True, verbose_name='DATA FINE')),
                ('budget_annuale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='CIFRA ANNUALE')),
                ('mesi', models.IntegerField(default=12, verbose_name='MESI')),
                ('budget_mensile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CIFRA MENSILE DA GESTIRE')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paghe.beneficiario', verbose_name='BENEFICIARIO')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paghe.tipoprogettoregionale', verbose_name='TIPO')),
            ],
            options={
                'verbose_name_plural': 'Progetti Regionali',
                'ordering': ['beneficiario__nome_cognome'],
            },
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='progetto',
            field=models.ManyToManyField(blank=True, to='paghe.progettoregionale', verbose_name='PROGETTI COLLEGATI'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='ente_bilaterale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paghe.tabellacasse'),
        ),
    ]
