# Generated by Django 6.0.5 on 2026-05-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0002_alter_contrattolavoro_note_post_it'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opzionisoftware',
            options={'verbose_name': 'Opzioni Software', 'verbose_name_plural': 'Opzioni Software'},
        ),
        migrations.AlterModelOptions(
            name='tabellacasse',
            options={'verbose_name_plural': 'Tabelle Casse (F2/E1)'},
        ),
        migrations.AlterModelOptions(
            name='tabellacontributiinps',
            options={'verbose_name_plural': 'Tabelle Contributi INPS'},
        ),
        migrations.AlterModelOptions(
            name='tabellamalattia',
            options={'verbose_name_plural': 'Tabelle Malattia'},
        ),
        migrations.AlterModelOptions(
            name='tabellascattianzianita',
            options={'verbose_name_plural': 'Tabelle Scatti Anzianità'},
        ),
        migrations.AlterModelOptions(
            name='testopreimpostato',
            options={'verbose_name_plural': 'Testi Preimpostati'},
        ),
    ]
