# Generated by Django 6.0.5 on 2026-05-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0003_alter_opzionisoftware_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='ore_calcolate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='ORE CALCOLATE'),
        ),
    ]
