# Generated by Django 6.0.5 on 2026-05-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0004_contrattolavoro_ore_calcolate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrattolavoro',
            name='ore_calcolate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='ORE CALCOLATE'),
        ),
    ]
