# Generated by Django 6.0.5 on 2026-05-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0005_alter_contrattolavoro_ore_calcolate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprogettoregionale',
            name='colore',
            field=models.CharField(default='#10b981', max_length=7, verbose_name='COLORE'),
        ),
    ]
