# Generated by Django 6.0.5 on 2026-05-24 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0007_livello_alter_parametriccnl_livello'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='logo_buste_paga',
            field=models.ImageField(blank=True, null=True, upload_to='loghi_studio/', verbose_name='LOGO BUSTE PAGA'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='testo_alert_contributi',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.testopreimpostato', verbose_name='TESTO ALERT CONTRIBUTI'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='testo_note_avvertenze',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.testopreimpostato', verbose_name='TESTO NOTE AVVERTENZE BUSTA'),
        ),
        migrations.AlterField(
            model_name='testopreimpostato',
            name='tipo',
            field=models.CharField(choices=[('MAIL', 'Modello Email'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('TESTO_PROGRAMMA', 'Testi del Programma')], default='MAIL', max_length=20, verbose_name='TIPO'),
        ),
    ]
