# Generated by Django 6.0.5 on 2026-05-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0008_opzionisoftware_logo_buste_paga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='tiny_api_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='TINY API KEY'),
        ),
    ]
