# Generated by Django 6.0.5 on 2026-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0009_opzionisoftware_tiny_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testopreimpostato',
            name='tipo',
            field=models.CharField(choices=[('MAIL', 'Modello Email'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('TESTO_PROGRAMMA', 'Testi del Programma'), ('CONTRATTO', 'Contratto'), ('RICEVUTA', 'Ricevuta'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto di Lavoro'), ('CARTELLINA', 'Cartellina'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('DEROGA_TFR', 'Deroga Concordata Anticipazione TFR'), ('LETTERA_LIBERA', 'Lettera Libera')], default='MAIL', max_length=50, verbose_name='TIPO'),
        ),
    ]
