# Generated by Django 6.0.5 on 2026-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0010_alter_testopreimpostato_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordEliminato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('datore', 'Datore'), ('lavoratore', 'Lavoratore'), ('beneficiario', 'Beneficiario'), ('contratto', 'Contratto'), ('progetto', 'Progetto Regionale'), ('parametro_ccnl', 'Parametro CCNL'), ('tabella_casse', 'Tabella Casse'), ('contributi_inps', 'Contributi INPS'), ('malattia', 'Malattia'), ('scatti_anzianita', 'Scatti Anzianità'), ('testo_preimpostato', 'Testo Preimpostato'), ('tipo_progetto', 'Tipo Progetto'), ('livello', 'Livello')], max_length=50, verbose_name='Tipo')),
                ('original_pk', models.CharField(max_length=255, verbose_name='PK originale')),
                ('dati', models.JSONField(verbose_name='Dati del record')),
                ('descrizione', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('eliminato_il', models.DateTimeField(auto_now_add=True, verbose_name='Eliminato il')),
            ],
            options={
                'verbose_name': 'Record eliminato',
                'verbose_name_plural': 'Record eliminati',
                'ordering': ['-eliminato_il'],
            },
        ),
    ]
