# Generated by Django 6.0.5 on 2026-05-25 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0011_recordeliminato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opzionisoftware',
            name='exe_lettore_pdf',
        ),
        migrations.RemoveField(
            model_name='opzionisoftware',
            name='path_locale_pdf',
        ),
        migrations.RemoveField(
            model_name='opzionisoftware',
            name='path_locale_posta',
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='email_mittente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='EMAIL MITTENTE'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='email_smtp_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='PASSWORD SMTP'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='email_smtp_port',
            field=models.IntegerField(default=587, verbose_name='PORTA SMTP'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='email_smtp_server',
            field=models.CharField(blank=True, max_length=255, verbose_name='SERVER SMTP'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='email_smtp_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='USERNAME SMTP'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='email_usa_programma_posta',
            field=models.BooleanField(default=False, verbose_name='USA PROGRAMMA DI POSTA'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='email_usa_tls',
            field=models.BooleanField(default=True, verbose_name='USA TLS'),
        ),
        migrations.CreateModel(
            name='DocumentoArchiviato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRATTO', 'Contratto'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('RICEVUTA', 'Ricevuta'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto'), ('DEROGA_TFR', 'Deroga TFR'), ('LETTERA_LIBERA', 'Lettera Libera'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('CARTELLINA', 'Cartellina'), ('ALTRO', 'Altro')], max_length=50, verbose_name='TIPO DOCUMENTO')),
                ('titolo', models.CharField(max_length=200, verbose_name='TITOLO')),
                ('file_path', models.CharField(max_length=512, verbose_name='PERCORSO FILE')),
                ('file_size', models.IntegerField(default=0, verbose_name='DIMENSIONE (bytes)')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='NOME FILE')),
                ('note', models.TextField(blank=True, verbose_name='NOTE')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('inviato', models.BooleanField(default=False, verbose_name='INVIATO VIA EMAIL')),
                ('inviato_il', models.DateTimeField(blank=True, null=True, verbose_name='INVIATO IL')),
                ('email_destinatario', models.EmailField(blank=True, max_length=254, verbose_name='DESTINATARIO EMAIL')),
                ('contratto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.contrattolavoro', verbose_name='CONTRATTO ASSOCIATO')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CREATO DA')),
                ('datore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.datorelavoro', verbose_name='DATORE ASSOCIATO')),
                ('lavoratore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.lavoratore', verbose_name='LAVORATORE ASSOCIATO')),
                ('modello_testo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.testopreimpostato', verbose_name='MODELLO TESTO USATO')),
            ],
            options={
                'verbose_name': 'Documento archiviato',
                'verbose_name_plural': 'Documenti archiviati',
                'ordering': ['-creato_il'],
            },
        ),
    ]
