# Generated by Django 6.0.5 on 2026-05-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0012_remove_opzionisoftware_exe_lettore_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='iban_studio',
            field=models.CharField(blank=True, max_length=50, verbose_name='IBAN STUDIO'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='testo_firma_email',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.testopreimpostato', verbose_name='TESTO FIRMA EMAIL'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='testo_note_footer_mail',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.testopreimpostato', verbose_name='TESTO NOTE FOOTER MAIL'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('BUSTA_PAGA', 'Busta Paga'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('RICEVUTA', 'Ricevuta'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto'), ('DEROGA_TFR', 'Deroga TFR'), ('LETTERA_LIBERA', 'Lettera Libera'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('CARTELLINA', 'Cartellina'), ('ALTRO', 'Altro')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
