# Generated by Django 6.0.5 on 2026-05-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0013_opzionisoftware_iban_studio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opzionisoftware',
            name='firma_email',
        ),
        migrations.RemoveField(
            model_name='opzionisoftware',
            name='note_footer_mail',
        ),
    ]
