# Generated by Django 6.0.5 on 2026-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0015_aggiungi_top_footer_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testopreimpostato',
            name='oggetto_titolo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='OGGETTO'),
        ),
    ]
