# Generated by Django 6.0.5 on 2026-05-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0016_oggetto_titolo_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opzionisoftware',
            name='cartella_backup',
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='denominazione_studio',
            field=models.CharField(blank=True, max_length=255, verbose_name='DENOMINAZIONE STUDIO'),
        ),
    ]
