# Generated by Django 6.0.5 on 2026-05-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0017_remove_opzionisoftware_cartella_backup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestorebackup',
            options={'ordering': ['-data_creazione'], 'verbose_name_plural': 'Gestione Backup'},
        ),
        migrations.AlterModelOptions(
            name='parametriccnl',
            options={'verbose_name_plural': '3. Parametri CCNL'},
        ),
    ]
