# Generated by Django 6.0.5 on 2026-05-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0020_alter_testopreimpostato_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='busta_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'BUSTA_PAGA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.testopreimpostato', verbose_name='Template Busta Paga'),
        ),
    ]
