# Generated by Django 6.0.5 on 2026-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0021_contrattolavoro_busta_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelloLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='NOME LISTA')),
                ('tipo_sorgente', models.CharField(choices=[('DATORE', 'Datori di Lavoro'), ('LAVORATORE', 'Lavoratori'), ('BENEFICIARIO', 'Beneficiari'), ('CONTRATTO', 'Contratti'), ('PROGETTO_REGIONALE', 'Progetti Regionali'), ('PAGOPA_INPS', 'PagoPA INPS')], max_length=30, verbose_name='TIPO SORGENTE')),
                ('configurazione_colonne', models.JSONField(default=list, help_text='Lista di oggetti: {label, field_path, larghezza, allineamento}', verbose_name='CONFIGURAZIONE COLONNE')),
                ('note', models.TextField(blank=True, verbose_name='NOTE')),
                ('is_default', models.BooleanField(default=False, verbose_name='MODELLO PREDEFINITO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='AGGIORNATO IL')),
            ],
            options={
                'verbose_name': 'Modello Lista',
                'verbose_name_plural': 'Modelli Lista',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('BUSTA_PAGA', 'Busta Paga'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('RICEVUTA', 'Ricevuta'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto'), ('DEROGA_TFR', 'Deroga TFR'), ('LETTERA_LIBERA', 'Lettera Libera'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('CARTELLINA', 'Cartellina'), ('LISTA', 'Lista Personalizzata'), ('ALTRO', 'Altro')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
