# Generated by Django 6.0.5 on 2026-05-28 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0022_modellolista_alter_documentoarchiviato_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiepilogoInvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('mese', models.IntegerField(verbose_name='MESE')),
                ('anno', models.IntegerField(verbose_name='ANNO')),
                ('totale_contratti', models.IntegerField(default=0, verbose_name='TOTALE CONTRATTI')),
                ('totale_ok', models.IntegerField(default=0, verbose_name='INVIATI CON SUCCESSO')),
                ('totale_errori', models.IntegerField(default=0, verbose_name='ERRORI')),
                ('dettaglio', models.JSONField(default=list, help_text='Lista di oggetti: {contratto_pk, datore, lavoratore, documento_pk, email_destinatario, inviato, errore}', verbose_name='DETTAGLIO')),
                ('archivio_zip_path', models.CharField(blank=True, max_length=512, verbose_name='PERCORSO ARCHIVIO ZIP')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CREATO DA')),
                ('modello_email', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MAIL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.testopreimpostato', verbose_name='MODELLO EMAIL')),
            ],
            options={
                'verbose_name': 'Riepilogo Invio',
                'verbose_name_plural': 'Riepiloghi Invio',
                'ordering': ['-creato_il'],
            },
        ),
    ]
