# Generated by Django 6.0.5 on 2026-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0023_riepilogoinvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riepilogoinvio',
            name='mese',
            field=models.IntegerField(choices=[(0, ''), (1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre')], verbose_name='MESE'),
        ),
    ]
