# Generated by Django 6.0.5 on 2026-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0024_alter_riepilogoinvio_mese'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametriccnl',
            name='ind_cert_qualita_mensile',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IND. CERT. QUALITÀ MENSILE'),
        ),
        migrations.AddField(
            model_name='parametriccnl',
            name='ind_funzione_mensile',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IND. FUNZIONE MENSILE'),
        ),
        migrations.AddField(
            model_name='parametriccnl',
            name='ind_minori_6_mensile_ft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IND. BAMBINI <6 FT MENSILE'),
        ),
        migrations.AddField(
            model_name='parametriccnl',
            name='ind_minori_6_mensile_pt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IND. BAMBINI <6 PT MENSILE'),
        ),
        migrations.AddField(
            model_name='parametriccnl',
            name='ind_piu_assistiti_mensile',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IND. PIÙ ASSISTITI MENSILE'),
        ),
        migrations.AddField(
            model_name='parametriccnl',
            name='minimo_mensile_ft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='MINIMO MENSILE FT'),
        ),
        migrations.AddField(
            model_name='parametriccnl',
            name='minimo_mensile_pt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='MINIMO MENSILE PT'),
        ),
    ]
