# Generated by Django 6.0.5 on 2026-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0025_parametriccnl_ind_cert_qualita_mensile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='usa_ind_cert_qualita_mensile',
            field=models.BooleanField(default=False, verbose_name='USA IND. CERT. QUALITÀ MENSILE'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='usa_ind_funzione_mensile',
            field=models.BooleanField(default=False, verbose_name='USA IND. FUNZIONE MENSILE'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='usa_ind_minori_6_mensile_ft',
            field=models.BooleanField(default=False, verbose_name='USA IND. MINORI <6 FT MENSILE'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='usa_ind_minori_6_mensile_pt',
            field=models.BooleanField(default=False, verbose_name='USA IND. MINORI <6 PT MENSILE'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='usa_ind_piu_assistiti_mensile',
            field=models.BooleanField(default=False, verbose_name='USA IND. PIÙ ASSISTITI MENSILE'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='usa_retribuzione_sostituzione',
            field=models.BooleanField(default=False, verbose_name='USA RETRIBUZIONE SOSTITUZIONE'),
        ),
    ]
