# Generated by Django 6.0.5 on 2026-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0026_aggiungi_usa_ind_mensili_retr_sost'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='giorni_malattia_usati_anno',
            field=models.IntegerField(default=0, verbose_name="GIORNI MALATTIA GIÀ USATI NELL'ANNO"),
        ),
    ]
