# Generated by Django 6.0.5 on 2026-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0027_contrattolavoro_giorni_malattia_usati_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='modalita_tfr',
            field=models.CharField(choices=[('INCLUSO', 'TFR Incluso nel lordo mensile'), ('SEPARATO_70', 'TFR Anticipo 70% (30% accantonato)'), ('SEPARATO_100', 'TFR 100% Accantonato a fine rapporto')], default='INCLUSO', max_length=12, verbose_name='Modalità TFR'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='paga_tfr',
            field=models.BooleanField(default=True, verbose_name='TFR (deprecato)'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('BUSTA_PAGA', 'Busta Paga'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('RICEVUTA', 'Ricevuta'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto'), ('DEROGA_TFR', 'Deroga TFR'), ('LETTERA_LIBERA', 'Lettera Libera'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('CARTELLINA', 'Cartellina'), ('LISTA', 'Lista Personalizzata'), ('PAGA_STANDARD', 'Busta Paga Standard'), ('NON_CONVIVENTE', 'Busta Non Convivente'), ('CONVIVENTI_CCNL', 'Busta Conviventi CCNL'), ('CALCOLO_INVERSO', 'Busta Calcolo Inverso'), ('BUSTA_MASSIVA', 'Busta Massiva'), ('MALATTIA', 'Busta Malattia'), ('NOTTURNO', 'Busta Notturna'), ('SOSTITUZIONE', 'Busta Sostituzione'), ('ALTRO', 'Altro')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
