# Generated by Django 6.0.5 on 2026-06-01 06:14

from django.db import migrations


def aggiorna_tfr_attivi(apps, schema_editor):
    ContrattoAttivo = apps.get_model('paghe', 'ContrattoAttivo')
    ContrattoAttivo.objects.filter(stato='ATTIVO').update(modalita_tfr='SEPARATO_100')


def revert_tfr_attivi(apps, schema_editor):
    ContrattoAttivo = apps.get_model('paghe', 'ContrattoAttivo')
    ContrattoAttivo.objects.filter(stato='ATTIVO').update(modalita_tfr='INCLUSO')


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0028_contrattolavoro_modalita_tfr_and_more'),
    ]

    operations = [
        migrations.RunPython(aggiorna_tfr_attivi, revert_tfr_attivi),
    ]
