# Generated by Django 6.0.5 on 2026-06-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0029_aggiorna_modalita_tfr_attivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='chromedriver_exe',
            field=models.CharField(blank=True, default='drivers/chromedriver.exe', max_length=512, verbose_name='PERCORSO CHROMEDRIVER EXE'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('BUSTA_PAGA', 'Busta Paga'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('RICEVUTA', 'Ricevuta'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto'), ('DEROGA_TFR', 'Deroga TFR'), ('LETTERA_LIBERA', 'Lettera Libera'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('CARTELLINA', 'Cartellina'), ('LISTA', 'Lista Personalizzata'), ('PAGA_STANDARD', 'Busta Paga Standard'), ('NON_CONVIVENTE', 'Busta Non Convivente'), ('CONVIVENTI_CCNL', 'Busta Conviventi CCNL'), ('CALCOLO_INVERSO', 'Busta Calcolo Inverso'), ('BUSTA_MASSIVA', 'Busta Massiva'), ('MALATTIA', 'Busta Malattia'), ('NOTTURNO', 'Busta Notturna'), ('SOSTITUZIONE', 'Busta Sostituzione'), ('BUSTA_TFR', 'Busta TFR'), ('LIQUIDAZIONE_TFR', 'Liquidazione TFR'), ('ALTRO', 'Altro')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
