# Generated by Django 6.0.5 on 2026-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0030_opzionisoftware_chromedriver_exe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServizioWebConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrome_user_data_dir', models.CharField(blank=True, help_text='Percorso alla user-data-dir di Chrome per mantenere la sessione INPS tra le procedure.', max_length=512, verbose_name='CARTELLA PROFILO CHROME')),
                ('headless', models.BooleanField(default=False, help_text='Esegue Chrome senza finestra grafica.', verbose_name='MODALITÀ HEADLESS')),
                ('timeout_elementi', models.IntegerField(default=10, help_text='Secondi massimi di attesa per la comparsa di elementi nelle pagine INPS.', verbose_name='TIMEOUT ATTESA (sec)')),
                ('link_inps_cessazione', models.URLField(blank=True, default='https://www.inps.it/it/it/dettaglio-scheda.it.schede-servizio-strumento.schede-servizi.cessazione-lavoratore-domestico.html', max_length=255, verbose_name='LINK INPS CESSAZIONE')),
            ],
            options={
                'verbose_name': 'Configurazione Servizi Web',
                'verbose_name_plural': 'Configurazioni Servizi Web',
            },
        ),
    ]
