# Generated by Django 6.0.5 on 2026-06-01 07:50

from django.db import migrations, models

URL_VECCHIA = "https://www.inps.it/it/it/dettaglio-scheda.it.schede-servizio-strumento.schede-servizi.cessazione-lavoratore-domestico.html"
URL_NUOVA = "https://www.inps.it/it/it/dettaglio-scheda.it.schede-servizio-strumento.schede-servizi.cessazione-lavoratore-domestico-50177.cessazione-lavoratore-domestico.html"

def aggiorna_link(apps, schema_editor):
    ServizioWebConfig = apps.get_model('paghe', 'ServizioWebConfig')
    ServizioWebConfig.objects.filter(link_inps_cessazione=URL_VECCHIA).update(link_inps_cessazione=URL_NUOVA)

class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0031_serviziowebconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviziowebconfig',
            name='link_inps_cessazione',
            field=models.URLField(blank=True, default='https://www.inps.it/it/it/dettaglio-scheda.it.schede-servizio-strumento.schede-servizi.cessazione-lavoratore-domestico-50177.cessazione-lavoratore-domestico.html', max_length=255, verbose_name='LINK INPS CESSAZIONE'),
        ),
        migrations.RunPython(aggiorna_link, migrations.RunPython.noop),
    ]
