# Generated by Django 6.0.5 on 2026-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0032_aggiorna_link_cessazione_inps'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziowebconfig',
            name='link_inps_pagopa',
            field=models.URLField(blank=True, default='https://serviziweb2.inps.it/PagamentiBollettiniLD/accessoUtente.do', max_length=255, verbose_name='LINK INPS PAGOPA'),
        ),
    ]
