# Generated by Django 6.0.5 on 2026-06-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0033_serviziowebconfig_link_inps_pagopa'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziowebconfig',
            name='delay_pausa',
            field=models.FloatField(default=0.5, help_text="Pausa in secondi tra le azioni dell'automazione (tra un click e l'altro). Valori tipici: 0.3-1.5.", verbose_name='PAUSA TRA AZIONI (sec)'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('BUSTA_PAGA', 'Busta Paga'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('RICEVUTA', 'Ricevuta'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto'), ('DEROGA_TFR', 'Deroga TFR'), ('LETTERA_LIBERA', 'Lettera Libera'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('CARTELLINA', 'Cartellina'), ('LISTA', 'Lista Personalizzata'), ('PAGA_STANDARD', 'Busta Paga Standard'), ('NON_CONVIVENTE', 'Busta Non Convivente'), ('CONVIVENTI_CCNL', 'Busta Conviventi CCNL'), ('CALCOLO_INVERSO', 'Busta Calcolo Inverso'), ('BUSTA_MASSIVA', 'Busta Massiva'), ('MALATTIA', 'Busta Malattia'), ('NOTTURNO', 'Busta Notturna'), ('SOSTITUZIONE', 'Busta Sostituzione'), ('BUSTA_TFR', 'Busta TFR'), ('LIQUIDAZIONE_TFR', 'Liquidazione TFR'), ('RIEPILOGO_PAGOPA', 'Riepilogo PagoPA'), ('ALTRO', 'Altro')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
