# Generated by Django 6.0.5 on 2026-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0034_serviziowebconfig_delay_pausa'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviziowebconfig',
            name='use_playwright',
            field=models.BooleanField(default=True, help_text="Usa Playwright invece di Selenium per l'automazione delle procedure web INPS.", verbose_name='USA PLAYWRIGHT'),
        ),
    ]
