# Generated by Django 6.0.6 on 2026-06-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0036_alter_documentoarchiviato_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametriccnl',
            name='fonte_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='FONTE URL'),
        ),
    ]
