# Generated by Django 6.0.5 on 2026-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0037_parametri_ccnl_fonte_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelloComposizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='NOME COMPOSIZIONE')),
                ('elementi', models.JSONField(default=list, help_text='Lista di oggetti: {tipo, label, template_pk, periodo_tipo, mese, anno}', verbose_name='ELEMENTI')),
                ('note', models.TextField(blank=True, verbose_name='NOTE')),
                ('is_default', models.BooleanField(default=False, verbose_name='PREDEFINITO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='AGGIORNATO IL')),
            ],
            options={
                'verbose_name': 'Modello Composizione',
                'verbose_name_plural': 'Modelli Composizione',
                'ordering': ['nome'],
            },
        ),
    ]
