# Generated by Django 6.0.6 on 2026-06-06 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0039_dati_composizioni_predefinite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('BUSTA_PAGA', 'Busta Paga'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('RICEVUTA', 'Ricevuta'), ('CUD', 'CUD'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto'), ('DEROGA_TFR', 'Deroga TFR'), ('LETTERA_LIBERA', 'Lettera Libera'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('CARTELLINA', 'Cartellina'), ('LISTA', 'Lista Personalizzata'), ('PAGA_STANDARD', 'Busta Paga Standard'), ('NON_CONVIVENTE', 'Busta Non Convivente'), ('CONVIVENTI_CCNL', 'Busta Conviventi CCNL'), ('CALCOLO_INVERSO', 'Busta Calcolo Inverso'), ('BUSTA_MASSIVA', 'Busta Massiva'), ('MALATTIA', 'Busta Malattia'), ('NOTTURNO', 'Busta Notturna'), ('SOSTITUZIONE', 'Busta Sostituzione'), ('BUSTA_TFR', 'Busta TFR'), ('LIQUIDAZIONE_TFR', 'Liquidazione TFR'), ('RIEPILOGO_PAGOPA', 'Riepilogo PagoPA'), ('PAGOPA', 'PagoPA INPS'), ('PAGOPA_MANUALE', 'PagoPA Manuale'), ('ALTRO', 'Altro')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
        migrations.CreateModel(
            name='LogOperazioneINPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_op', models.CharField(choices=[('APERTURA_ASSUNZIONE', 'Apertura Assunzione'), ('SALVATAGGIO_CODICE', 'Salvataggio Codice Rapporto'), ('APERTURA_CESSAZIONE', 'Apertura Cessazione'), ('APERTURA_PAGOPA_MANUALE', 'Apertura PagoPA Manuale'), ('CARICATO_PDF_PAGOPA_MANUALE', 'Caricato PDF PagoPA Manuale')], max_length=40, verbose_name='TIPO OPERAZIONE')),
                ('dettaglio', models.TextField(blank=True, verbose_name='DETTAGLIO')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='DATA')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paghe.contrattolavoro', verbose_name='CONTRATTO')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UTENTE')),
            ],
            options={
                'verbose_name': 'Log operazione INPS',
                'verbose_name_plural': 'Log operazioni INPS',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
