# Generated by Django 6.0.6 on 2026-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0040_alter_documentoarchiviato_tipo_logoperazioneinps'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='causale_cessazione',
            field=models.CharField(blank=True, max_length=30, verbose_name='CAUSALE CESSAZIONE'),
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='data_fine',
            field=models.DateField(blank=True, null=True, verbose_name='DATA FINE RAPPORTO'),
        ),
        migrations.AlterField(
            model_name='logoperazioneinps',
            name='tipo_op',
            field=models.CharField(choices=[('APERTURA_ASSUNZIONE', 'Apertura Assunzione'), ('SALVATAGGIO_CODICE', 'Salvataggio Codice Rapporto'), ('APERTURA_CESSAZIONE', 'Apertura Cessazione'), ('SALVATAGGIO_DATA_FINE', 'Salvataggio Data Fine'), ('APERTURA_PAGOPA_MANUALE', 'Apertura PagoPA Manuale'), ('CARICATO_PDF_PAGOPA_MANUALE', 'Caricato PDF PagoPA Manuale')], max_length=40, verbose_name='TIPO OPERAZIONE'),
        ),
    ]
