# Generated by Django 6.0.6 on 2026-06-07 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0041_contrattolavoro_causale_cessazione_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BustaPaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mese', models.IntegerField(verbose_name='MESE')),
                ('anno', models.IntegerField(verbose_name='ANNO')),
                ('tipo_calcolo', models.CharField(help_text='CONVIVENTE / NON_CONVIVENTE / SOSTITUZIONE', max_length=20, verbose_name='TIPO CALCOLO')),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('APPROVATA', 'Approvata'), ('ARCHIVIATA', 'Archiviata')], default='BOZZA', max_length=10, verbose_name='STATO')),
                ('data_calcolo', models.DateTimeField(auto_now_add=True, verbose_name='DATA CALCOLO')),
                ('data_modifica', models.DateTimeField(auto_now=True, verbose_name='ULTIMA MODIFICA')),
                ('budget_mensile', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BUDGET MENSILE')),
                ('ore_mensili', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ORE MENSILI')),
                ('ore_inps', models.IntegerField(verbose_name='ORE INPS')),
                ('ore_settimanali', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='ORE SETTIMANALI')),
                ('paga_oraria_lorda', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='PAGA ORARIA LORDA')),
                ('paga_base_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PAGA BASE TOTALE')),
                ('totale_indennita', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOTALE INDENNITÀ')),
                ('scatti_totale', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='SCATTI TOTALI')),
                ('totale_lordo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TOTALE LORDO')),
                ('contributi_inps_orario', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='INPS ORARIO')),
                ('contributi_inps_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INPS TOTALE')),
                ('contributi_inps_fascia', models.CharField(blank=True, max_length=10, verbose_name='FASCIA INPS')),
                ('contributi_cassa_orario', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='CASSA ORARIO')),
                ('contributi_cassa_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CASSA TOTALE')),
                ('contributi_cassa_nome', models.CharField(blank=True, max_length=100, verbose_name='NOME CASSA')),
                ('totale_contributi', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOTALE CONTRIBUTI')),
                ('convivenza_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CONVIVENZA TOTALE')),
                ('totale_accantonati', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RATEI ACCANTONATI')),
                ('netto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='NETTO')),
                ('indennita_json', models.JSONField(blank=True, default=dict, verbose_name='INDENNITÀ (JSON)')),
                ('ratei_pagati_json', models.JSONField(blank=True, default=list, verbose_name='RATEI (JSON)')),
                ('scatti_dettaglio_json', models.JSONField(blank=True, default=dict, verbose_name='SCATTI (JSON)')),
                ('progetti_json', models.JSONField(blank=True, default=list, verbose_name='PROGETTI (JSON)')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paghe.contrattolavoro', verbose_name='CONTRATTO')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.documentoarchiviato', verbose_name='DOCUMENTO PDF')),
            ],
            options={
                'verbose_name': 'Busta Paga',
                'verbose_name_plural': 'Buste Paga',
                'ordering': ['-anno', '-mese', 'contratto__datore__nome_cognome'],
                'unique_together': {('contratto', 'mese', 'anno')},
            },
        ),
    ]
