# Generated by Django 6.0.6 on 2026-06-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0042_bustapaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustapaga',
            name='tfr_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='DATI LIQUIDAZIONE TFR'),
        ),
    ]
