# Generated by Django 6.0.6 on 2026-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0043_bustapaga_tfr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoarchiviato',
            name='data_stampa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DATA STAMPA'),
        ),
        migrations.AddField(
            model_name='documentoarchiviato',
            name='stampato',
            field=models.BooleanField(default=False, verbose_name='STAMPATO'),
        ),
    ]
