# Generated by Django 6.0.6 on 2026-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0044_documentoarchiviato_stampato'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='exe_lettore_pdf',
            field=models.CharField(blank=True, max_length=512, verbose_name='LINK AL LETTORE PDF (per stampa diretta)'),
        ),
    ]
