# Generated by Django 6.0.6 on 2026-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0045_opzionisoftware_exe_lettore_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'ordering': ['cognome', 'nome'], 'verbose_name_plural': 'Anagrafica: Beneficiari'},
        ),
        migrations.AlterModelOptions(
            name='datorelavoro',
            options={'ordering': ['cognome', 'nome'], 'verbose_name_plural': 'Anagrafica: Datori'},
        ),
        migrations.AlterModelOptions(
            name='lavoratore',
            options={'ordering': ['cognome', 'nome'], 'verbose_name_plural': 'Anagrafica: Lavoratori'},
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cognome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='COGNOME'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NOME'),
        ),
        migrations.AddField(
            model_name='datorelavoro',
            name='cognome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='COGNOME'),
        ),
        migrations.AddField(
            model_name='datorelavoro',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NOME'),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='cognome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='COGNOME'),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NOME'),
        ),
    ]
