# Generated by Django 6.0.6 on 2026-06-09 05:57

from django.db import migrations


def popola_nome_cognome(apps, schema_editor):
    modelli = ['DatoreLavoro', 'Lavoratore', 'Beneficiario']
    for nome_modello in modelli:
        Modello = apps.get_model('paghe', nome_modello)
        for obj in Modello.objects.all():
            if obj.nome or obj.cognome:
                continue  # già popolato
            nc = (obj.nome_cognome or '').strip()
            if not nc:
                continue
            parts = nc.split(' ', 1)
            obj.nome = parts[0]
            obj.cognome = parts[1] if len(parts) > 1 else ''
            obj.save(update_fields=['nome', 'cognome'])


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0046_alter_beneficiario_options_and_more'),
    ]

    operations = [
        migrations.RunPython(popola_nome_cognome),
    ]
