# Generated by Django 6.0.5 on 2026-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0047_popola_nome_cognome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='INDIRIZZO EMAIL'),
        ),
        migrations.AlterField(
            model_name='datorelavoro',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='INDIRIZZO EMAIL'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='email_destinatario',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='DESTINATARIO EMAIL'),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='INDIRIZZO EMAIL'),
        ),
    ]
