# Generated by Django 6.0.6 on 2026-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0048_alter_beneficiario_email_alter_datorelavoro_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoperazioneinps',
            name='tipo_op',
            field=models.CharField(choices=[('APERTURA_ASSUNZIONE', 'Apertura Assunzione'), ('SALVATAGGIO_CODICE', 'Salvataggio Codice Rapporto'), ('APERTURA_CESSAZIONE', 'Apertura Cessazione'), ('SALVATAGGIO_DATA_FINE', 'Salvataggio Data Fine'), ('APERTURA_PAGOPA_MANUALE', 'Apertura PagoPA Manuale'), ('CARICATO_PDF_PAGOPA_MANUALE', 'Caricato PDF PagoPA Manuale'), ('APERTURA_PAGOPA_AUTO', 'Apertura PagoPA Automatica'), ('COMPLETATO_PAGOPA_AUTO', 'Completato PagoPA Automatico'), ('GENERATO_PDF_PAGOPA', 'Generato PDF PagoPA')], max_length=40, verbose_name='TIPO OPERAZIONE'),
        ),
    ]
