# Generated by Django 6.0.6 on 2026-06-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0050_alter_documentoarchiviato_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CUAnnuale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(verbose_name='ANNO')),
                ('modalita', models.CharField(choices=[('AUTOMATICA', 'Automatica (da BustaPaga)'), ('SEMI_AUTOMATICA', 'Semi-Automatica (13 mensilità)'), ('MANUALE', 'Manuale')], default='AUTOMATICA', max_length=20, verbose_name='MODALITÀ')),
                ('reddito_lordo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='REDDITO LORDO')),
                ('contributi_inps_lav', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CONTRIBUTI INPS LAV.')),
                ('contributi_cassa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CONTRIBUTI CASSA')),
                ('contributi_totali', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CONTRIBUTI TOTALI')),
                ('netto_corrisposto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='NETTO CORRISPOSTO')),
                ('tfr_accantonato', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TFR ACCANTONATO')),
                ('indennita_convivenza', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='INDENNITÀ CONVIVENZA')),
                ('imponibile_fiscale', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IMPONIBILE FISCALE')),
                ('dettaglio_mensile', models.JSONField(blank=True, default=dict, verbose_name='DETTAGLIO MENSILE (13 mensilità)')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('aggiornato_il', models.DateTimeField(auto_now=True, verbose_name='AGGIORNATO IL')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cu_annuali', to='paghe.contrattolavoro', verbose_name='CONTRATTO')),
                ('creato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CREATO DA')),
            ],
            options={
                'verbose_name': 'CU Annuale',
                'verbose_name_plural': 'CU Annuali',
                'ordering': ['-anno', '-creato_il'],
                'unique_together': {('contratto', 'anno', 'modalita')},
            },
        ),
    ]
