# Generated by Django 6.0.6 on 2026-06-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0051_cuannuale'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='contributi_trimestre_versati',
            field=models.BooleanField(default=False, verbose_name='CONTRIBUTI TRIMESTRE VERSATI'),
        ),
    ]
