# Generated by Django 6.0.6 on 2026-06-10 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0052_contrattolavoro_contributi_trimestre_versati'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnticipoTFR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IMPORTO')),
                ('data', models.DateField(verbose_name='DATA')),
                ('note', models.TextField(blank=True, verbose_name='NOTE')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paghe.contrattolavoro', verbose_name='CONTRATTO')),
            ],
            options={
                'verbose_name': 'Anticipo TFR',
                'verbose_name_plural': 'Anticipi TFR',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='LogInvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='TIPO DOCUMENTO')),
                ('data_ora', models.DateTimeField(auto_now_add=True, verbose_name='DATA E ORA')),
                ('destinatario', models.CharField(blank=True, max_length=200, verbose_name='DESTINATARIO')),
                ('esito', models.CharField(choices=[('OK', 'OK'), ('ERRORE', 'Errore')], default='OK', max_length=10, verbose_name='ESITO')),
                ('messaggio_errore', models.TextField(blank=True, verbose_name='MESSAGGIO ERRORE')),
                ('contratto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.contrattolavoro', verbose_name='CONTRATTO')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UTENTE')),
            ],
            options={
                'verbose_name': 'Log invio email',
                'verbose_name_plural': 'Log invii email',
                'ordering': ['-data_ora'],
            },
        ),
    ]
