# Generated by Django 6.0.6 on 2026-06-10 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0053_anticipotfr_loginvioemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificaContratto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50, verbose_name='CAMPO MODIFICATO')),
                ('valore_precedente', models.TextField(blank=True, verbose_name='VALORE PRECEDENTE')),
                ('valore_nuovo', models.TextField(blank=True, verbose_name='VALORE NUOVO')),
                ('data_modifica', models.DateTimeField(auto_now_add=True, verbose_name='DATA MODIFICA')),
                ('contratto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiche', to='paghe.contrattolavoro')),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UTENTE')),
            ],
            options={
                'verbose_name': 'Modifica Contratto',
                'verbose_name_plural': 'Modifiche Contratti',
                'ordering': ['-data_modifica'],
            },
        ),
    ]
