# Generated by Django 6.0.5 on 2026-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0054_modificacontratto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorciatoiaTastiera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(help_text="Identificativo univoco, es. 'nav-datore', 'nav-lavoratori'", max_length=100, unique=True, verbose_name='ID menu')),
                ('label', models.CharField(max_length=100, verbose_name='Etichetta')),
                ('tasto', models.CharField(blank=True, max_length=1, null=True, unique=True, verbose_name='Tasto scorciatoia')),
                ('icona', models.CharField(blank=True, default='', max_length=50, verbose_name='Icona Bootstrap')),
                ('ordinamento', models.IntegerField(default=0, verbose_name='Ordine')),
                ('attiva', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Scorciatoia da tastiera',
                'verbose_name_plural': 'Scorciatoie da tastiera',
                'ordering': ['ordinamento'],
            },
        ),
    ]
