# Generated by Django 6.0.6 on 2026-06-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0055_scorciatoiatastiera'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoDatore',
            fields=[
                ('datore', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='paghe.datorelavoro', verbose_name='DATORE')),
                ('password', models.CharField(max_length=128, verbose_name='PASSWORD (hash)')),
                ('accesso_abilitato', models.BooleanField(default=False, verbose_name='ACCESSO ABILITATO')),
                ('ultimo_accesso', models.DateTimeField(blank=True, null=True, verbose_name='ULTIMO ACCESSO')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('modificato_il', models.DateTimeField(auto_now=True, verbose_name='MODIFICATO IL')),
            ],
            options={
                'verbose_name': 'Accesso datore',
                'verbose_name_plural': 'Accessi datori',
            },
        ),
        migrations.AddField(
            model_name='documentoarchiviato',
            name='visibile_al_datore',
            field=models.BooleanField(default=False, verbose_name='VISIBILE AL DATORE'),
        ),
    ]
