# Generated by Django 6.0.6 on 2026-06-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0056_accessodatore_documentoarchiviato_visibile_al_datore'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaModificaDatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANAGRAFICA', 'Modifica Anagrafica'), ('CONTRATTO', 'Modifica Contratto'), ('PROGETTO', 'Modifica Progetto'), ('CESSAZIONE', 'Richiesta Cessazione'), ('MALATTIA', 'Richiesta Malattia / Sostituzione'), ('CU', 'Richiesta Certificazione Unica'), ('TESTO_LIBERO', 'Altro (testo libero)')], max_length=20, verbose_name='TIPO RICHIESTA')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='CAMPO')),
                ('etichetta_campo', models.CharField(blank=True, max_length=200, verbose_name='ETICHETTA CAMPO')),
                ('valore_attuale', models.TextField(blank=True, verbose_name='VALORE ATTUALE')),
                ('valore_richiesto', models.TextField(blank=True, verbose_name='VALORE RICHIESTO')),
                ('stato', models.CharField(choices=[('INVIATA', 'Inviata'), ('VISTA', 'Vista'), ('ACCETTATA', 'Accettata'), ('RIFIUTATA', 'Rifiutata')], default='INVIATA', max_length=20, verbose_name='STATO')),
                ('nota_datore', models.TextField(blank=True, verbose_name='NOTA DATORE')),
                ('nota_admin', models.TextField(blank=True, verbose_name='NOTA ADMIN')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('gestito_il', models.DateTimeField(blank=True, null=True, verbose_name='GESTITO IL')),
                ('contratto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.contrattolavoro', verbose_name='CONTRATTO')),
                ('datore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paghe.datorelavoro', verbose_name='DATORE')),
            ],
            options={
                'verbose_name': 'Richiesta modifica datore',
                'verbose_name_plural': 'Richieste modifica datori',
                'ordering': ['-creato_il'],
            },
        ),
    ]
