# Generated by Django 6.0.6 on 2026-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0057_richiestamodificadatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestamodificadatore',
            name='data_eliminazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DATA ELIMINAZIONE'),
        ),
        migrations.AddField(
            model_name='richiestamodificadatore',
            name='eliminata',
            field=models.BooleanField(default=False, verbose_name='ELIMINATA'),
        ),
    ]
