# Generated by Django 6.0.6 on 2026-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0058_richiestamodificadatore_eliminata'),
    ]

    operations = [
        migrations.AddField(
            model_name='datorelavoro',
            name='cap',
            field=models.CharField(blank=True, max_length=5, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='datorelavoro',
            name='provincia',
            field=models.CharField(blank=True, max_length=4, verbose_name='PROVINCIA'),
        ),
    ]
