# Generated by Django 6.0.6 on 2026-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0059_datorelavoro_provincia_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorebackup',
            name='file_db',
            field=models.FileField(blank=True, null=True, upload_to='backups_db/'),
        ),
    ]
