# Generated by Django 6.0.6 on 2026-06-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0060_gestorebackup_file_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('tipo', models.CharField(choices=[('SCADENZA', 'Scadenza'), ('APPUNTAMENTO', 'Appuntamento'), ('PROMEMORIA', 'Promemoria')], default='PROMEMORIA', max_length=20, verbose_name='Tipo')),
                ('completato', models.BooleanField(default=False, verbose_name='Completato')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
            ],
            options={
                'verbose_name': 'Appuntamento',
                'verbose_name_plural': 'Agenda Appuntamenti',
                'ordering': ['data', 'pk'],
            },
        ),
    ]
