# Generated by Django 6.0.6 on 2026-06-13 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0061_appuntamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelloDocumentale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRATTO', 'Contratto'), ('CUD', 'CUD'), ('CARTELLINA', 'Cartellina'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto di Lavoro'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('LETTERA_LIBERA', 'Lettera Libera'), ('DEROGA_TFR', 'Deroga Concordata Anticipazione TFR'), ('RICEVUTA', 'Ricevuta'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('LISTA_STAMPA', 'Lista Stampa')], max_length=50, verbose_name='TIPO DOCUMENTO')),
                ('codice', models.CharField(max_length=50, unique=True, verbose_name='CODICE')),
                ('titolo', models.CharField(blank=True, default='', max_length=200, verbose_name='TITOLO')),
                ('corpo_testo', models.TextField(verbose_name='CORPO TESTO')),
                ('note_interne', models.TextField(blank=True, verbose_name='NOTE INTERNE')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='CREATO IL')),
                ('modificato_il', models.DateTimeField(auto_now=True, verbose_name='MODIFICATO IL')),
                ('versione', models.IntegerField(default=1, verbose_name='VERSIONE')),
                ('font_family', models.CharField(default='Arial', max_length=100, verbose_name='FONT PDF')),
                ('font_size', models.IntegerField(default=11, verbose_name='DIMENSIONE FONT')),
            ],
            options={
                'verbose_name': 'Modello documentale',
                'verbose_name_plural': 'Modelli documentali',
                'ordering': ['tipo', 'codice'],
            },
        ),
        migrations.AddField(
            model_name='documentoarchiviato',
            name='modello_documentale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.modellodocumentale', verbose_name='MODELLO DOCUMENTALE USATO'),
        ),
    ]
