# Generated by Django 6.0.6 on 2026-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0063_migra_testi_documentali'),
    ]

    operations = [
        migrations.AddField(
            model_name='modellodocumentale',
            name='oggetto_titolo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='OGGETTO'),
        ),
        migrations.AlterField(
            model_name='modellodocumentale',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('CUD', 'CUD'), ('CARTELLINA', 'Cartellina'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto di Lavoro'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('LETTERA_LIBERA', 'Lettera Libera'), ('DEROGA_TFR', 'Deroga Concordata Anticipazione TFR'), ('RICEVUTA', 'Ricevuta'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('LISTA_STAMPA', 'Lista Stampa'), ('BUSTA_PAGA', 'Busta Paga'), ('MAIL', 'Modello Email'), ('TESTO_PROGRAMMA', 'Testi del Programma'), ('TOP_DOCUMENTO', 'Top Documento'), ('FOOTER_DOCUMENTO', 'Footer Documento')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
