# Generated by Django 6.0.6 on 2026-06-13 16:00

from django.db import migrations


def _copia_testi(apps, schema_editor):
    TestoPreimpostato = apps.get_model('paghe', 'TestoPreimpostato')
    ModelloDocumentale = apps.get_model('paghe', 'ModelloDocumentale')
    ContrattoLavoro = apps.get_model('paghe', 'ContrattoLavoro')
    OpzioniSoftware = apps.get_model('paghe', 'OpzioniSoftware')
    RiepilogoInvio = apps.get_model('paghe', 'RiepilogoInvio')
    DocumentoArchiviato = apps.get_model('paghe', 'DocumentoArchiviato')

    id_map = {}
    # Tipi da migrare (quelli non ancora copiati in 0063)
    tipi_da_migrare = {'BUSTA_PAGA', 'MAIL', 'TESTO_PROGRAMMA', 'TOP_DOCUMENTO', 'FOOTER_DOCUMENTO'}

    # Codici già presenti in ModelloDocumentale
    codici_esistenti = set(ModelloDocumentale.objects.values_list('codice', flat=True))

    for tp in TestoPreimpostato.objects.filter(tipo__in=tipi_da_migrare).iterator():
        if tp.codice in codici_esistenti:
            continue  # già migrato
        md = ModelloDocumentale.objects.create(
            tipo=tp.tipo,
            codice=tp.codice,
            titolo=tp.oggetto_titolo,
            oggetto_titolo=tp.oggetto_titolo,
            corpo_testo=tp.corpo_testo,
            note_interne=tp.note_interne,
        )
        id_map[tp.pk] = md.pk

    if not id_map:
        return  # nulla da migrare

    # Aggiorna FK su ContrattoLavoro.busta_template
    for cl in ContrattoLavoro.objects.filter(busta_template_id__in=id_map.keys()).iterator():
        cl.busta_template_id = id_map[cl.busta_template_id]
        cl.save(update_fields=['busta_template_id'])

    # Aggiorna FK su OpzioniSoftware
    opz = OpzioniSoftware.objects.first()
    if opz:
        campi = ['testo_alert_contributi', 'testo_note_avvertenze', 'testo_note_footer_mail', 'testo_firma_email']
        changed = False
        for field in campi:
            old_id = getattr(opz, field + '_id', None)
            if old_id and old_id in id_map:
                setattr(opz, field + '_id', id_map[old_id])
                changed = True
        if changed:
            opz.save()

    # Aggiorna FK su RiepilogoInvio.modello_email
    for ri in RiepilogoInvio.objects.filter(modello_email_id__in=id_map.keys()).iterator():
        ri.modello_email_id = id_map[ri.modello_email_id]
        ri.save(update_fields=['modello_email_id'])

    # Aggiorna FK su DocumentoArchiviato.modello_testo
    for doc in DocumentoArchiviato.objects.filter(modello_testo_id__in=id_map.keys()).iterator():
        doc.modello_documentale_id = id_map[doc.modello_testo_id]
        doc.modello_testo_id = id_map[doc.modello_testo_id]
        doc.save(update_fields=['modello_documentale_id', 'modello_testo_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0064_modellodocumentale_oggetto_titolo_and_more'),
    ]

    operations = [
        migrations.RunPython(_copia_testi, migrations.RunPython.noop),
    ]
