# Generated by Django 6.0.6 on 2026-06-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0065_copia_testi_preimpostati'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrattolavoro',
            name='busta_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'BUSTA_PAGA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.modellodocumentale', verbose_name='Template Busta Paga'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='modello_testo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.modellodocumentale', verbose_name='MODELLO TESTO USATO'),
        ),
        migrations.AlterField(
            model_name='opzionisoftware',
            name='testo_alert_contributi',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.modellodocumentale', verbose_name='TESTO ALERT CONTRIBUTI'),
        ),
        migrations.AlterField(
            model_name='opzionisoftware',
            name='testo_firma_email',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.modellodocumentale', verbose_name='TESTO FIRMA EMAIL'),
        ),
        migrations.AlterField(
            model_name='opzionisoftware',
            name='testo_note_avvertenze',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.modellodocumentale', verbose_name='TESTO NOTE AVVERTENZE BUSTA'),
        ),
        migrations.AlterField(
            model_name='opzionisoftware',
            name='testo_note_footer_mail',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'TESTO_PROGRAMMA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='paghe.modellodocumentale', verbose_name='TESTO NOTE FOOTER MAIL'),
        ),
        migrations.AlterField(
            model_name='riepilogoinvio',
            name='modello_email',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MAIL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paghe.modellodocumentale', verbose_name='MODELLO EMAIL'),
        ),
    ]
