# Generated by Django 6.0.6 on 2026-06-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0066_alter_contrattolavoro_busta_template_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestoPreimpostato',
        ),
    ]
