# Generated by Django 6.0.6 on 2026-06-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0068_cifra_password_smtp'),
    ]

    operations = [
    ]
