# Generated by Django 6.0.6 on 2026-06-14 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0069_refactoring_modelli'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bustapaga',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cuannuale',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='nome_studio',
            field=models.CharField(blank=True, default='CIRCOLO MCL ISILI di GABRIELE CORONGIU', max_length=255, verbose_name='NOME STUDIO'),
        ),
        migrations.AlterField(
            model_name='accessodatore',
            name='datore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='accesso', serialize=False, to='paghe.datorelavoro', verbose_name='DATORE'),
        ),
        migrations.AlterField(
            model_name='anticipotfr',
            name='contratto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipi_tfr', to='paghe.contrattolavoro', verbose_name='CONTRATTO'),
        ),
        migrations.AlterField(
            model_name='bustapaga',
            name='contratto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buste', to='paghe.contrattolavoro', verbose_name='CONTRATTO'),
        ),
        migrations.AlterField(
            model_name='bustapaga',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buste_paga', to='paghe.documentoarchiviato', verbose_name='DOCUMENTO PDF'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='busta_template',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'BUSTA_PAGA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratti_template_busta', to='paghe.modellodocumentale', verbose_name='Template Busta Paga'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='datore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratti_come_datore', to='paghe.datorelavoro'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='ente_bilaterale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratti_ente', to='paghe.tabellacasse'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='lavoratore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratti_come_lavoratore', to='paghe.lavoratore'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='ore_calcolate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='ORE CALCOLATE'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='parametri_minimi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratti_parametrizzati', to='paghe.parametriccnl'),
        ),
        migrations.AlterField(
            model_name='cuannuale',
            name='creato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cu_annuali_create', to=settings.AUTH_USER_MODEL, verbose_name='CREATO DA'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='contratto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_archiviati', to='paghe.contrattolavoro', verbose_name='CONTRATTO ASSOCIATO'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='creato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_creati', to=settings.AUTH_USER_MODEL, verbose_name='CREATO DA'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='datore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_archiviati', to='paghe.datorelavoro', verbose_name='DATORE ASSOCIATO'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='lavoratore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_archiviati', to='paghe.lavoratore', verbose_name='LAVORATORE ASSOCIATO'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='modello_documentale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_generati', to='paghe.modellodocumentale', verbose_name='MODELLO DOCUMENTALE USATO'),
        ),
        migrations.AlterField(
            model_name='loginvioemail',
            name='contratto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_invii_email', to='paghe.contrattolavoro', verbose_name='CONTRATTO'),
        ),
        migrations.AlterField(
            model_name='loginvioemail',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_invii_email', to=settings.AUTH_USER_MODEL, verbose_name='UTENTE'),
        ),
        migrations.AlterField(
            model_name='logoperazioneinps',
            name='contratto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_operazioni_inps', to='paghe.contrattolavoro', verbose_name='CONTRATTO'),
        ),
        migrations.AlterField(
            model_name='logoperazioneinps',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_operazioni_inps', to=settings.AUTH_USER_MODEL, verbose_name='UTENTE'),
        ),
        migrations.AlterField(
            model_name='modificacontratto',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifiche_contratti', to=settings.AUTH_USER_MODEL, verbose_name='UTENTE'),
        ),
        migrations.AlterField(
            model_name='opzionisoftware',
            name='dati_studio',
            field=models.TextField(blank=True, verbose_name='INDIRIZZO STUDIO'),
        ),
        migrations.AlterField(
            model_name='parametriccnl',
            name='livello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parametri_ccnl', to='paghe.livello', verbose_name='LIVELLO'),
        ),
        migrations.AlterField(
            model_name='progettoregionale',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='paghe.beneficiario', verbose_name='BENEFICIARIO'),
        ),
        migrations.AlterField(
            model_name='progettoregionale',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='progetti_di_tipo', to='paghe.tipoprogettoregionale', verbose_name='TIPO'),
        ),
        migrations.AlterField(
            model_name='richiestamodificadatore',
            name='contratto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='richieste_modifica', to='paghe.contrattolavoro', verbose_name='CONTRATTO'),
        ),
        migrations.AlterField(
            model_name='richiestamodificadatore',
            name='datore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_modifica', to='paghe.datorelavoro', verbose_name='DATORE'),
        ),
        migrations.AlterField(
            model_name='riepilogoinvio',
            name='creato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riepiloghi_invii', to=settings.AUTH_USER_MODEL, verbose_name='CREATO DA'),
        ),
        migrations.AlterField(
            model_name='riepilogoinvio',
            name='modello_email',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'MAIL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riepiloghi_email', to='paghe.modellodocumentale', verbose_name='MODELLO EMAIL'),
        ),
        migrations.AddConstraint(
            model_name='bustapaga',
            constraint=models.UniqueConstraint(fields=('contratto', 'mese', 'anno'), name='unique_busta_contratto_mese_anno'),
        ),
        migrations.AddConstraint(
            model_name='cuannuale',
            constraint=models.UniqueConstraint(fields=('contratto', 'anno', 'modalita'), name='unique_cu_contratto_anno_modalita'),
        ),
    ]
