# Generated by Django 6.0.5 on 2026-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0070_alter_bustapaga_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='cap_studio',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAP STUDIO'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='comune_studio',
            field=models.CharField(blank=True, max_length=100, verbose_name='COMUNE STUDIO'),
        ),
    ]
