# Generated by Django 6.0.5 on 2026-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0071_comune_cap_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='cap',
            field=models.CharField(blank=True, max_length=5, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='provincia',
            field=models.CharField(blank=True, max_length=4, verbose_name='PROVINCIA'),
        ),
    ]
