# Generated by Django 6.0.6 on 2026-06-15 18:07

import paghe.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0072_beneficiario_cap_beneficiario_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opzionisoftware',
            name='email_smtp_password',
            field=paghe.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='PASSWORD SMTP (cifrata)'),
        ),
    ]
