# Generated by Django 6.0.6 on 2026-06-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0073_cifra_email_smtp_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessodatore',
            options={'ordering': ['datore__nome_cognome'], 'verbose_name': 'Accesso datore', 'verbose_name_plural': 'Accessi datori'},
        ),
        migrations.AlterModelOptions(
            name='parametriccnl',
            options={'ordering': ['livello', 'anno'], 'verbose_name_plural': '3. Parametri CCNL'},
        ),
        migrations.AlterModelOptions(
            name='serviziowebconfig',
            options={'ordering': ['id'], 'verbose_name': 'Configurazione Servizi Web', 'verbose_name_plural': 'Configurazioni Servizi Web'},
        ),
        migrations.AlterModelOptions(
            name='tabellacasse',
            options={'ordering': ['codice'], 'verbose_name_plural': 'Tabelle Casse (F2/E1)'},
        ),
        migrations.AlterModelOptions(
            name='tabellacontributiinps',
            options={'ordering': ['descrizione'], 'verbose_name_plural': 'Tabelle Contributi INPS'},
        ),
        migrations.AlterModelOptions(
            name='tabellamalattia',
            options={'ordering': ['anzianita'], 'verbose_name_plural': 'Tabelle Malattia'},
        ),
        migrations.AlterModelOptions(
            name='tabellascattianzianita',
            options={'ordering': ['livello'], 'verbose_name_plural': 'Tabelle Scatti Anzianità'},
        ),
        migrations.AlterModelOptions(
            name='tipoprogettoregionale',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Tipi di Progetto Regionale'},
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nome_cognome',
            field=models.CharField(max_length=100, verbose_name='COGNOME E NOME'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='data_assunzione',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='is_convivente',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Lavoratore Convivente (Sì/No)'),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='stato',
            field=models.CharField(choices=[('ATTIVO', 'Attivo'), ('CESSATO', 'Cessato')], db_index=True, default='ATTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='contrattolavoro',
            name='tipo_contratto',
            field=models.CharField(choices=[('INDETERMINATO', 'Indeterminato'), ('DETERMINATO', 'Determinato')], db_index=True, default='INDETERMINATO', max_length=15),
        ),
        migrations.AlterField(
            model_name='datorelavoro',
            name='nome_cognome',
            field=models.CharField(max_length=100, verbose_name='COGNOME E NOME'),
        ),
        migrations.AlterField(
            model_name='datorelavoro',
            name='pin_inps',
            field=models.CharField(blank=True, max_length=50, verbose_name='PIN INPS - PIN TESSERA SANITARIA O CIE'),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='nome_cognome',
            field=models.CharField(max_length=100, verbose_name='COGNOME E NOME'),
        ),
    ]
