# Generated by Django 6.0.6 on 2026-06-15 19:45

import paghe.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0074_modelli_ordinamento_db_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='ricorrenza',
            field=models.CharField(choices=[('NESSUNA', 'Nessuna'), ('SETTIMANALE', 'Settimanale'), ('MENSILE', 'Mensile'), ('ANNUALE', 'Annuale')], default='NESSUNA', max_length=20, verbose_name='Ricorrenza'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, validators=[paghe.fields.MultiEmailValidator(message='Inserire uno o piu indirizzi email validi separati da ;')], verbose_name='INDIRIZZO EMAIL'),
        ),
        migrations.AlterField(
            model_name='datorelavoro',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, validators=[paghe.fields.MultiEmailValidator(message='Inserire uno o piu indirizzi email validi separati da ;')], verbose_name='INDIRIZZO EMAIL'),
        ),
        migrations.AlterField(
            model_name='documentoarchiviato',
            name='email_destinatario',
            field=models.CharField(blank=True, default='', max_length=200, validators=[paghe.fields.MultiEmailValidator(message='Inserire uno o piu indirizzi email validi separati da ;')], verbose_name='DESTINATARIO EMAIL'),
        ),
        migrations.AlterField(
            model_name='lavoratore',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, validators=[paghe.fields.MultiEmailValidator(message='Inserire uno o piu indirizzi email validi separati da ;')], verbose_name='INDIRIZZO EMAIL'),
        ),
    ]
