# Generated by Django 6.0.6 on 2026-06-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0075_appuntamento_ricorrenza_alter_beneficiario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuntamento',
            name='colore',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Colore'),
        ),
        migrations.AddField(
            model_name='appuntamento',
            name='ora',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora'),
        ),
    ]
