# Generated by Django 6.0.6 on 2026-06-16 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0076_aggiungi_ora_colore_appuntamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttivitaMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Attività')),
                ('categoria', models.CharField(choices=[('BUSTE_PAGA', 'Buste Paga'), ('CONTRIBUTI', 'Contributi'), ('CU', 'Certificazione Unica'), ('DOCUMENTI', 'Documenti'), ('VARIE', 'Varie')], default='VARIE', max_length=30, verbose_name='Categoria')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('obbligatorio', models.BooleanField(default=False, verbose_name='Obbligatoria')),
            ],
            options={
                'verbose_name': 'Attività Mensile',
                'verbose_name_plural': 'Attività Mensili',
                'ordering': ['categoria', 'ordine'],
            },
        ),
        migrations.CreateModel(
            name='CompletamentoMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(verbose_name='Anno')),
                ('mese', models.IntegerField(verbose_name='Mese')),
                ('completato', models.BooleanField(default=False, verbose_name='Completato')),
                ('completato_il', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('attivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completamenti', to='paghe.attivitamensile', verbose_name='Attività')),
                ('completato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Completato da')),
            ],
            options={
                'verbose_name': 'Completamento Mensile',
                'verbose_name_plural': 'Completamenti Mensili',
                'ordering': ['-anno', '-mese', 'attivita__categoria', 'attivita__ordine'],
                'unique_together': {('attivita', 'anno', 'mese')},
            },
        ),
    ]
