# Generated by Django 6.0.6 on 2026-06-16 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0077_attivita_mensile_completamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='dati_precedenti',
            field=models.JSONField(blank=True, null=True, verbose_name='Dati precedenti'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='dati_successivi',
            field=models.JSONField(blank=True, null=True, verbose_name='Dati successivi'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='indirizzo_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='pk_oggetto',
            field=models.CharField(blank=True, max_length=50, verbose_name='PK Oggetto'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='azione',
            field=models.CharField(max_length=255, verbose_name='Azione'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='dettagli',
            field=models.TextField(blank=True, verbose_name='Dettagli'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='modello_coinvolto',
            field=models.CharField(max_length=50, verbose_name='Modello'),
        ),
    ]
