# Generated by Django 6.0.6 on 2026-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0078_auditlog_campi_estesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='cartella_backup',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='CARTELLA BACKUP'),
        ),
        migrations.AlterField(
            model_name='gestorebackup',
            name='file_db',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gestorebackup',
            name='file_json',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
