# Generated by Django 6.0.6 on 2026-06-16 13:58

from django.db import migrations


def converti_percorsi(apps, schema_editor):
    GestoreBackup = apps.get_model('paghe', 'GestoreBackup')
    from django.conf import settings
    import os

    for backup in GestoreBackup.objects.all():
        cambiato = False

        vecchio_json = backup.file_json
        if vecchio_json and not os.path.isabs(vecchio_json):
            abs_path = os.path.join(settings.MEDIA_ROOT, vecchio_json)
            backup.file_json = abs_path if os.path.isfile(abs_path) else ''
            cambiato = True
        elif not vecchio_json:
            backup.file_json = ''
            cambiato = True

        vecchio_db = backup.file_db
        if vecchio_db and not os.path.isabs(vecchio_db):
            abs_path = os.path.join(settings.MEDIA_ROOT, vecchio_db)
            backup.file_db = abs_path if os.path.isfile(abs_path) else ''
            cambiato = True
        elif not vecchio_db:
            backup.file_db = ''
            cambiato = True

        if cambiato:
            backup.save(update_fields=['file_json', 'file_db'])


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0079_cartella_backup_opzioni'),
    ]

    operations = [
        migrations.RunPython(converti_percorsi, reverse_code=migrations.RunPython.noop),
    ]
