# Generated by Django 6.0.6 on 2026-06-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0080_converti_percorsi_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='notifiche_scadenze_attive',
            field=models.BooleanField(default=False, verbose_name='NOTIFICHE SCADENZE ATTIVE'),
        ),
    ]
