# Generated by Django 6.0.6 on 2026-06-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0081_opzionisoftware_notifiche_scadenze_attive'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceISTAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(unique=True, verbose_name='ANNO')),
                ('indice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='INDICE FOI')),
            ],
            options={
                'verbose_name': 'Indice ISTAT FOI',
                'verbose_name_plural': 'Indici ISTAT FOI',
                'ordering': ['-anno'],
            },
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='applica_rivalutazione_tfr',
            field=models.BooleanField(default=False, verbose_name='Applica rivalutazione TFR'),
        ),
    ]
