# Generated by Django 6.0.6 on 2026-06-18 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0082_indiceistat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrattolavoro',
            name='contratto_rinnovato_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rinnovi_successivi', to='paghe.contrattolavoro', verbose_name='Rinnovato dal contratto'),
        ),
    ]
