# Generated by Django 6.0.6 on 2026-06-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0083_contratto_rinnovato_da'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='giorni_ritenzione_backup',
            field=models.IntegerField(default=30, verbose_name='GIORNI RITENZIONE BACKUP'),
        ),
    ]
