# Generated by Django 6.0.6 on 2026-06-26 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('paghe', '0086_ccnl_articolo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloUtente',
            fields=[
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profilo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ruolo', models.CharField(choices=[('ADMIN', 'Amministratore'), ('OPERATORE', 'Operatore'), ('CONSULENTE', 'Consulente'), ('DATORE', 'Datore di Lavoro')], default='OPERATORE', max_length=20)),
                ('permessi_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Profilo utente',
                'verbose_name_plural': 'Profili utente',
            },
        ),
        migrations.AddField(
            model_name='contrattolavoro',
            name='visibile_a',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='VISIBILE A'),
        ),
        migrations.AddField(
            model_name='datorelavoro',
            name='visibile_a',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='VISIBILE A'),
        ),
        migrations.AddField(
            model_name='lavoratore',
            name='visibile_a',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='VISIBILE A'),
        ),
    ]
