# Generated by Django 6.0.6 on 2026-06-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0087_profiloutente_contrattolavoro_visibile_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opzionisoftware',
            name='soglia_paga_1_contributi',
            field=models.DecimalField(decimal_places=2, default=9.61, max_digits=6, verbose_name='SOGLIA PAGA 1 CONTRIBUTI (FINO A)'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='soglia_paga_2_contributi',
            field=models.DecimalField(decimal_places=2, default=11.7, max_digits=6, verbose_name='SOGLIA PAGA 2 CONTRIBUTI (FINO A)'),
        ),
        migrations.AlterField(
            model_name='modellodocumentale',
            name='tipo',
            field=models.CharField(choices=[('CONTRATTO', 'Contratto'), ('CUD', 'CUD'), ('CARTELLINA', 'Cartellina'), ('RIEPILOGO_RAPPORTO', 'Riepilogo Rapporto di Lavoro'), ('LETTERA_ASSUNZIONE', 'Lettera Assunzione'), ('LETTERA_LICENZIAMENTO', 'Lettera Licenziamento'), ('LETTERA_DIMISSIONI', 'Lettera Dimissioni'), ('LETTERA_LIBERA', 'Lettera Libera'), ('DEROGA_TFR', 'Deroga Concordata Anticipazione TFR'), ('RICEVUTA', 'Ricevuta'), ('RICHIESTA_CUD', 'Richiesta CUD'), ('PDF_INIZIO', 'Inizio Rapporto'), ('PDF_FINE', 'Fine Rapporto'), ('PDF_RISCONTRO', 'Riscontro Comune'), ('LISTA_STAMPA', 'Lista Stampa'), ('BUSTA_PAGA', 'Busta Paga'), ('LUL', 'Libro Unico Lavoro'), ('MAIL', 'Modello Email'), ('TESTO_PROGRAMMA', 'Testi del Programma'), ('TOP_DOCUMENTO', 'Top Documento'), ('FOOTER_DOCUMENTO', 'Footer Documento')], max_length=50, verbose_name='TIPO DOCUMENTO'),
        ),
    ]
