# Generated by Django 6.0.6 on 2026-06-28 10:09

from django.db import migrations, models


def popola_soglia_mesi(apps, schema_editor):
    TabellaMalattia = apps.get_model('paghe', 'TabellaMalattia')
    mapping = {
        "ANZIANITA' FINO A 6 MESI": 6,
        "ANZIANITA' DA PIU' DI 6 MESI A 2 ANNI": 24,
        "ANZIANITA' OLTRE I 2 ANNI": 999,
    }
    for rec in TabellaMalattia.objects.all():
        if rec.anzianita in mapping:
            rec.soglia_mesi = mapping[rec.anzianita]
            rec.save()


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0088_opzionisoftware_soglia_paga_1_contributi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabellamalattia',
            name='soglia_mesi',
            field=models.IntegerField(default=0, verbose_name='SOGLIA MESI'),
        ),
        migrations.RunPython(popola_soglia_mesi, reverse_code=migrations.RunPython.noop),
    ]
