# Generated by Django 6.0.6 on 2026-06-28 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0089_tabellamalattia_soglia_mesi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opzionisoftware',
            old_name='link_python',
            new_name='disponibile_1',
        ),
        migrations.RenameField(
            model_name='opzionisoftware',
            old_name='link_chromedriver',
            new_name='disponibile_2',
        ),
    ]
