# Generated by Django 6.0.6 on 2026-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0090_rinomina_disponibile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustapaga',
            name='contributi_inps_quota_datore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INPS QUOTA DATORE TOTALE'),
        ),
        migrations.AddField(
            model_name='bustapaga',
            name='contributi_inps_quota_lavoratore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='INPS QUOTA LAVORATORE TOTALE'),
        ),
        migrations.AlterField(
            model_name='opzionisoftware',
            name='disponibile_1',
            field=models.URLField(blank=True, default='https://www.python.org', max_length=255, verbose_name='LINK DISPONIBILE 1'),
        ),
        migrations.AlterField(
            model_name='opzionisoftware',
            name='disponibile_2',
            field=models.URLField(blank=True, default='https://googlechromelabs.github.io/chrome-for-testing/', max_length=255, verbose_name='LINK DISPONIBILE 2'),
        ),
    ]
