# Generated by Django 6.0.6 on 2026-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0091_bustapaga_quote_contributi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'verbose_name_plural': 'Anagrafica: Beneficiari'},
        ),
        migrations.AlterModelOptions(
            name='datorelavoro',
            options={'verbose_name_plural': 'Anagrafica: Datori'},
        ),
        migrations.AlterModelOptions(
            name='lavoratore',
            options={'verbose_name_plural': 'Anagrafica: Lavoratori'},
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='banca_iban',
            field=models.CharField(blank=True, max_length=255, verbose_name='BANCA IBAN'),
        ),
        migrations.AddField(
            model_name='opzionisoftware',
            name='intestatario_iban',
            field=models.CharField(blank=True, max_length=255, verbose_name='INTESTATARIO IBAN'),
        ),
    ]
