# Generated by Django 6.0.6 on 2026-07-03 10:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paghe', '0092_alter_beneficiario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContrattoLavoro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('stato', models.CharField(choices=[('ATTIVO', 'Attivo'), ('CESSATO', 'Cessato')], db_index=True, default='ATTIVO', max_length=10)),
                ('codice_rapporto_inps', models.CharField(blank=True, max_length=50)),
                ('data_fine', models.DateField(blank=True, null=True, verbose_name='DATA FINE RAPPORTO')),
                ('causale_cessazione', models.CharField(blank=True, max_length=30, verbose_name='CAUSALE CESSAZIONE')),
                ('data_assunzione', models.DateField(db_index=True)),
                ('data_inizio_tfr', models.DateField(blank=True, null=True)),
                ('tipo_contratto', models.CharField(choices=[('INDETERMINATO', 'Indeterminato'), ('DETERMINATO', 'Determinato')], db_index=True, default='INDETERMINATO', max_length=15)),
                ('applica_scatti', models.BooleanField(default=True, verbose_name='Applica scatti')),
                ('applica_rivalutazione_tfr', models.BooleanField(default=False, verbose_name='Applica rivalutazione TFR')),
                ('paga_tfr', models.BooleanField(default=True, verbose_name='TFR (deprecato)')),
                ('modalita_tfr', models.CharField(choices=[('INCLUSO', 'TFR Incluso nel lordo mensile'), ('SEPARATO_70', 'TFR Anticipo 70% (30% accantonato)'), ('SEPARATO_100', 'TFR 100% Accantonato a fine rapporto')], default='INCLUSO', max_length=12, verbose_name='Modalità TFR')),
                ('paga_13ma', models.BooleanField(default=True, verbose_name='TREDICESIMA')),
                ('paga_festivi', models.BooleanField(default=True, verbose_name='FESTIVI')),
                ('paga_ferie', models.BooleanField(default=True, verbose_name='FERIE')),
                ('ore_mav_custom', models.IntegerField(blank=True, null=True, verbose_name='MODIFICA ORE PAGOPA')),
                ('ore_calcolate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='ORE CALCOLATE')),
                ('ind_certificazione_qualita', models.BooleanField(default=False, verbose_name='CERTIFICAZIONE DI QUALITÀ')),
                ('ind_piu_persone_non_conv', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE (NON CONV)')),
                ('ind_minori_non_conv', models.BooleanField(default=False, verbose_name='IND. MINORI < 6 ANNI (NON CONV)')),
                ('ind_piu_persone_qualita', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE + QUALITÀ')),
                ('ind_minori_qualita', models.BooleanField(default=False, verbose_name='IND. MINORI + QUALITÀ')),
                ('ind_assistenza_piu_persone_ft', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE (CONV FT)')),
                ('ind_assistenza_piu_persone_pt', models.BooleanField(default=False, verbose_name='IND. PIÙ PERSONE (CONV PT)')),
                ('ind_minori_6_anni_ft', models.BooleanField(default=False, verbose_name='IND. MINORI < 6 ANNI (CONV FT)')),
                ('applica_notturno_assistenza', models.BooleanField(default=False, verbose_name='NOTTURNO ASSISTENZA (20-08)')),
                ('applica_notturno_presenza', models.BooleanField(default=False, verbose_name='NOTTURNO PRESENZA (21-08)')),
                ('applica_notturno_base', models.BooleanField(default=False, verbose_name='NOTTURNO PAGA BASE')),
                ('applica_notturno_20', models.BooleanField(default=False, verbose_name='NOTTURNO PAGA BASE (20%)')),
                ('paga_notturno_tfr', models.BooleanField(default=False, verbose_name='NOTTURNO TFR')),
                ('paga_notturno_13ma', models.BooleanField(default=False, verbose_name='NOTTURNO TREDICESIMA')),
                ('paga_notturno_festivi', models.BooleanField(default=False, verbose_name='NOTTURNO FESTIVI')),
                ('paga_notturno_ferie', models.BooleanField(default=False, verbose_name='NOTTURNO FERIE')),
                ('ind_funzione_conviventi', models.BooleanField(default=False, verbose_name='INDENNITÀ FUNZIONE')),
                ('ind_conviventi_ft_54h', models.BooleanField(default=False, verbose_name='CONVIVENTI FT (54H)')),
                ('ind_conviventi_pt_30h', models.BooleanField(default=False, verbose_name='CONVIVENTI PT (30H)')),
                ('is_convivente', models.BooleanField(db_index=True, default=False, verbose_name='Lavoratore Convivente (Sì/No)')),
                ('usa_ind_funzione_mensile', models.BooleanField(default=False, verbose_name='USA IND. FUNZIONE MENSILE')),
                ('usa_ind_minori_6_mensile_ft', models.BooleanField(default=False, verbose_name='USA IND. MINORI <6 FT MENSILE')),
                ('usa_ind_minori_6_mensile_pt', models.BooleanField(default=False, verbose_name='USA IND. MINORI <6 PT MENSILE')),
                ('usa_ind_piu_assistiti_mensile', models.BooleanField(default=False, verbose_name='USA IND. PIÙ ASSISTITI MENSILE')),
                ('usa_ind_cert_qualita_mensile', models.BooleanField(default=False, verbose_name='USA IND. CERT. QUALITÀ MENSILE')),
                ('usa_retribuzione_sostituzione', models.BooleanField(default=False, verbose_name='USA RETRIBUZIONE SOSTITUZIONE')),
                ('paga_pranzo', models.BooleanField(default=False, verbose_name='CONVIVENZA PRANZO')),
                ('paga_cena', models.BooleanField(default=False, verbose_name='CONVIVENZA CENA')),
                ('paga_alloggio', models.BooleanField(default=False, verbose_name='CONVIVENZA ALLOGGIO')),
                ('note_post_it', models.TextField(blank=True, null=True, verbose_name='NOTE / POST-IT')),
                ('giorni_malattia_usati_anno', models.IntegerField(default=0, verbose_name="GIORNI MALATTIA GIÀ USATI NELL'ANNO")),
                ('contributi_trimestre_versati', models.BooleanField(default=False, verbose_name='CONTRIBUTI TRIMESTRE VERSATI')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('busta_template', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'tipo': 'BUSTA_PAGA'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paghe.modellodocumentale', verbose_name='Template Busta Paga')),
                ('contratto_rinnovato_da', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paghe.contrattolavoro', verbose_name='Rinnovato dal contratto')),
                ('datore', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paghe.datorelavoro')),
                ('ente_bilaterale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paghe.tabellacasse')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lavoratore', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paghe.lavoratore')),
                ('parametri_minimi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='paghe.parametriccnl')),
            ],
            options={
                'verbose_name': 'historical contratto lavoro',
                'verbose_name_plural': 'historical 6. Anagrafica: Contratti',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
