VARIABILI_DISPONIBILI = [
    {
        "categoria": "LAYOUT",
        "items": [
            {"var": "INIZIO_PAGINA", "label": "Inizio pagina"},
            {"var": "STOP_INIZIO_PAGINA", "label": "Stop inizio pagina"},
            {"var": "CAMBIA_PAGINA", "label": "Cambia pagina"},
            {"var": "FINE_PAGINA", "label": "Fine pagina"},
            {"var": "STOP_FINE_PAGINA", "label": "Stop fine pagina"},
            {"var": "TOP_DOCUMENTO", "label": "Top documento"},
            {"var": "FOOTER_DOCUMENTO", "label": "Footer documento"},
            {"var": "LOGO_PROGRAMMA,80", "label": "Logo programma (80%)"},
            {"var": "LOGO_BUSTE_PAGA,80", "label": "Logo buste (80%)"},
            {"var": "LINEA", "label": "Linea"},
            {"var": "HR", "label": "HR"},
            {"var": "RIGA_VUOTA", "label": "Riga vuota"},
        ],
    },
    {
        "categoria": "STUDIO",
        "items": [
            {"var": "NOME_SOFTWARE", "label": "Nome software"},
            {"var": "NOME_STUDIO", "label": "Nome studio"},
            {"var": "DENOMINAZIONE_STUDIO", "label": "Denominazione studio"},
            {"var": "INDIRIZZO_STUDIO", "label": "Indirizzo studio"},
            {"var": "COMUNE_STUDIO", "label": "Comune studio"},
            {"var": "CAP_STUDIO", "label": "CAP studio"},
            {"var": "INDIRIZZO_STUDIO_COMPLETO", "label": "Indirizzo completo"},
            {"var": "TELEFONO_STUDIO", "label": "Telefono studio"},
            {"var": "EMAIL_STUDIO", "label": "Email studio"},
            {"var": "IBAN_STUDIO", "label": "IBAN studio"},
            {"var": "INTESTATARIO_IBAN", "label": "Intestatario IBAN"},
            {"var": "BANCA_IBAN", "label": "Banca IBAN"},
            {"var": "VERSIONE_SOFTWARE", "label": "Versione software"},
            {"var": "NOTE_FOOTER_MAIL", "label": "Note footer mail"},
            {"var": "FIRMA_EMAIL", "label": "Firma email"},
            {"var": "ALERT_CONTRIBUTI", "label": "Alert contributi"},
            {"var": "TESTO_NOTE_AVVERTENZE", "label": "Note avvertenze"},
            {"var": "SOGLIA_ORE_CONTRIBUTI", "label": "Soglia ore contributi"},
            {"var": "RATEO_FERIE_MENSILE", "label": "Rateo ferie mensile"},
            {"var": "ANNO_GESTIONE", "label": "Anno gestione"},
            {"var": "MESI_ANNUALI_STD", "label": "Mesi annuali std"},
            {"var": "GIORNI_MENSILI_STD", "label": "Giorni mensili std"},
            {"var": "SETTIMANE_ANNUALI_STD", "label": "Settimane annuali std"},
            {"var": "LOGO_PROGRAMMA", "label": "Logo programma"},
            {"var": "LOGO_BUSTE_PAGA", "label": "Logo buste paga"},
        ],
    },
    {
        "categoria": "DATORE",
        "items": [
            {"var": "NOME_DATORE", "label": "Nome datore"},
            {"var": "NOME_COGNOME_DATORE", "label": "Nome e cognome"},
            {"var": "NOME_DATORE_SOLO", "label": "Solo nome datore"},
            {"var": "COGNOME_DATORE_SOLO", "label": "Solo cognome datore"},
            {"var": "CF_DATORE", "label": "CF datore"},
            {"var": "INDIRIZZO_DATORE", "label": "Indirizzo datore"},
            {"var": "PAESE_DATORE", "label": "Comune datore"},
            {"var": "PROVINCIA_DATORE", "label": "Provincia datore"},
            {"var": "CAP_DATORE", "label": "CAP datore"},
            {"var": "MAIL_DATORE", "label": "Mail datore"},
            {"var": "TELEFONO_DATORE", "label": "Telefono datore"},
            {"var": "NOTE_DATORE", "label": "Note datore"},
        ],
    },
    {
        "categoria": "LAVORATORE",
        "items": [
            {"var": "NOME_LAVORATORE", "label": "Nome lavoratore"},
            {"var": "NOME_COGNOME_LAVORATORE", "label": "Nome e cognome"},
            {"var": "NOME_LAVORATORE_SOLO", "label": "Solo nome lavoratore"},
            {"var": "COGNOME_LAVORATORE_SOLO", "label": "Solo cognome lavoratore"},
            {"var": "CF_LAVORATORE", "label": "CF lavoratore"},
            {"var": "INDIRIZZO_LAVORATORE", "label": "Indirizzo lavoratore"},
            {"var": "PAESE_LAVORATORE", "label": "Comune lavoratore"},
            {"var": "EMAIL_LAVORATORE", "label": "Email lavoratore"},
            {"var": "TELEFONO_LAVORATORE", "label": "Telefono lavoratore"},
            {"var": "FERIE_PREGRESSE", "label": "Ferie pregresse"},
            {"var": "SCATTI_ANZIANITA_MATURATI", "label": "Scatti anzianit\u00e0 maturati"},
            {"var": "NOTE_LAVORATORE", "label": "Note lavoratore"},
        ],
    },
    {
        "categoria": "BENEFICIARIO",
        "items": [
            {"var": "NOME_BENEFICIARIO", "label": "Nome beneficiario"},
            {"var": "NOME_COGNOME_BENEFICIARIO", "label": "Nome e cognome"},
            {"var": "NOME_BENEFICIARIO_SOLO", "label": "Solo nome beneficiario"},
            {"var": "COGNOME_BENEFICIARIO_SOLO", "label": "Solo cognome beneficiario"},
            {"var": "CF_BENEFICIARIO", "label": "CF beneficiario"},
            {"var": "INDIRIZZO_BENEFICIARIO", "label": "Indirizzo beneficiario"},
            {"var": "COMUNE_BENEFICIARIO", "label": "Comune beneficiario"},
            {"var": "EMAIL_BENEFICIARIO", "label": "Email beneficiario"},
            {"var": "TELEFONO_BENEFICIARIO", "label": "Telefono beneficiario"},
            {"var": "NOTE_BENEFICIARIO", "label": "Note beneficiario"},
        ],
    },
    {
        "categoria": "CONTRATTO",
        "items": [
            {"var": "TIPO_CONTRATTO", "label": "Tipo contratto"},
            {"var": "STATO_CONTRATTO", "label": "Stato contratto"},
            {"var": "DATA_ASSUNZIONE", "label": "Data assunzione"},
            {"var": "DATA_FINE", "label": "Data fine"},
            {"var": "CAUSALE_CESSAZIONE", "label": "Causale cessazione"},
            {"var": "DATA_INIZIO_TFR", "label": "Data inizio TFR"},
            {"var": "ORE_SETTIMANALI", "label": "Ore settimanali"},
            {"var": "ORE_MENSILI", "label": "Ore mensili"},
            {"var": "ORE_INPS", "label": "Ore INPS"},
            {"var": "CODICE_RAPPORTO_INPS", "label": "Codice rapporto INPS"},
            {"var": "PARAMETRI_MINIMI", "label": "Parametri minimi"},
            {"var": "ENTE_BILATERALE", "label": "Ente bilaterale"},
            {"var": "RETRIBUZIONE_TOTALE", "label": "Retribuzione totale"},
            {"var": "CONTRIBUTI_MENSILI", "label": "Contributi mensili"},
            {"var": "CONTRIBUTI_TRIMESTRALI", "label": "Contributi trimestrali"},
            {"var": "CONTRIBUTI_ANNUALI", "label": "Contributi annuali"},
            {"var": "GIORNI_MALATTIA_USATI", "label": "Giorni malattia usati"},
            {"var": "NOTE_CONTRATTO", "label": "Note contratto"},
        ],
    },
    {
        "categoria": "PROGETTO",
        "items": [
            {"var": "TIPO_PROGETTO", "label": "Tipo progetto"},
            {"var": "DATA_INIZIO_PROGETTO", "label": "Data inizio progetto"},
            {"var": "DATA_FINE", "label": "Data fine progetto"},
            {"var": "MESI_PROGETTO", "label": "Mesi progetto"},
            {"var": "BUDGET_ANNUALE", "label": "Budget annuale"},
            {"var": "BUDGET_MENSILE", "label": "Budget mensile"},
        ],
    },
    {
        "categoria": "CCNL / RETRIBUZIONE",
        "items": [
            {"var": "LIVELLO_CCNL", "label": "Livello CCNL"},
            {"var": "PAGA_BASE", "label": "Paga base"},
            {"var": "PAGA_ORARIA", "label": "Paga oraria"},
            {"var": "APPLICA_SCATTI", "label": "Applica scatti"},
            {"var": "PAGA_TFR", "label": "Paga TFR"},
            {"var": "PAGA_13MA", "label": "Paga 13ma"},
            {"var": "PAGA_FESTIVI", "label": "Paga festivi"},
            {"var": "PAGA_FERIE", "label": "Paga ferie"},
            {"var": "RETRIBUZIONE_SOSTITUZIONE", "label": "Retrib. sostituzione"},
            {"var": "MINIMO_MENSILE_FT", "label": "Minimo mensile FT"},
            {"var": "MINIMO_MENSILE_PT", "label": "Minimo mensile PT"},
            {"var": "ANNO_PARAMETRI_CCNL", "label": "Anno parametri CCNL"},
            {"var": "DESCRIZIONE_LUNGA_CCNL", "label": "Descrizione lunga CCNL"},
        ],
    },
    {
        "categoria": "CCNL IMPORTI MENSILI",
        "items": [
            {"var": "IND_FUNZIONE_MENSILE", "label": "Ind. funzione mensile"},
            {"var": "IND_MINORI_6_MENSILE_FT", "label": "Ind. minori <6 FT mensile"},
            {"var": "IND_MINORI_6_MENSILE_PT", "label": "Ind. minori <6 PT mensile"},
            {"var": "IND_PIU_ASSISTITI_MENSILE", "label": "Ind. pi\u00f9 assistiti mensile"},
            {"var": "IND_CERT_QUALITA_MENSILE", "label": "Ind. cert. qualit\u00e0 mensile"},
        ],
    },
    {
        "categoria": "BOOLEAN CONTRATTO MENSILI",
        "items": [
            {"var": "USA_IND_FUNZIONE_MENSILE", "label": "Usa ind. funzione mensile"},
            {"var": "USA_IND_MINORI_6_MENSILE_FT", "label": "Usa ind. minori <6 FT mensile"},
            {"var": "USA_IND_MINORI_6_MENSILE_PT", "label": "Usa ind. minori <6 PT mensile"},
            {"var": "USA_IND_PIU_ASSISTITI_MENSILE", "label": "Usa ind. pi\u00f9 assistiti mensile"},
            {"var": "USA_IND_CERT_QUALITA_MENSILE", "label": "Usa ind. cert. qualit\u00e0 mensile"},
            {"var": "USA_RETRIBUZIONE_SOSTITUZIONE", "label": "Usa retrib. sostituzione"},
        ],
    },
    {
        "categoria": "INDENNITA'",
        "items": [
            {"var": "IND_CERTIF_QUALITA", "label": "Certificazione qualit\u00e0"},
            {"var": "IND_PIU_PERSONE_NC", "label": "Pi\u00f9 persone (NC)"},
            {"var": "IND_MINORI_NC", "label": "Minori (NC)"},
            {"var": "IND_PIU_PERSONE_QUAL", "label": "Pi\u00f9 persone qual."},
            {"var": "IND_MINORI_QUAL", "label": "Minori qual."},
            {"var": "IND_PIU_PERSONE_FT", "label": "Pi\u00f9 persone FT"},
            {"var": "IND_PIU_PERSONE_PT", "label": "Pi\u00f9 persone PT"},
            {"var": "IND_MINORI_FT", "label": "Minori FT"},
        ],
    },
    {
        "categoria": "NOTTURNO",
        "items": [
            {"var": "NOTTURNO_ASSISTENZA", "label": "Notturno assistenza"},
            {"var": "NOTTURNO_PRESENZA", "label": "Notturno presenza"},
            {"var": "NOTTURNO_BASE", "label": "Notturno base"},
            {"var": "NOTTURNO_20", "label": "Notturno 20%"},
            {"var": "NOTT_TFR", "label": "Notturno TFR"},
            {"var": "NOTT_13MA", "label": "Notturno 13ma"},
            {"var": "NOTT_FESTIVI", "label": "Notturno festivi"},
            {"var": "NOTT_FERIE", "label": "Notturno ferie"},
        ],
    },
    {
        "categoria": "CONVIVENTI / VITTO",
        "items": [
            {"var": "IND_FUNZIONE", "label": "Ind. funzione"},
            {"var": "CONVIVENTI_FT", "label": "Conviventi FT"},
            {"var": "CONVIVENTI_PT", "label": "Conviventi PT"},
            {"var": "IS_CONVIVENTE", "label": "\u00c8 convivente"},
            {"var": "CONVIVENZA", "label": "Presta convivenza"},
            {"var": "PAGA_PRANZO", "label": "Paga pranzo"},
            {"var": "PAGA_CENA", "label": "Paga cena"},
            {"var": "PAGA_ALLOGGIO", "label": "Paga alloggio"},
        ],
    },
    {
        "categoria": "RATEI",
        "items": [
            {"var": "RATEO_TFR", "label": "Rateo TFR"},
            {"var": "RATEO_13MA", "label": "Rateo 13ma"},
            {"var": "RATEO_TREDICESIMA", "label": "Rateo tredicesima"},
            {"var": "RATEO_FESTIVI", "label": "Rateo festivi"},
            {"var": "RATEO_FERIE", "label": "Rateo ferie"},
        ],
    },
    {
        "categoria": "BUSTA PAGA",
        "items": [
            {"var": "MESE_BUSTA", "label": "Mese busta"},
            {"var": "ANNO_BUSTA", "label": "Anno busta"},
            {"var": "STATO_BUSTA", "label": "Stato busta"},
            {"var": "TIPO_CALCOLO_BUSTA", "label": "Tipo calcolo busta"},
            {"var": "DATA_CALCOLO_BUSTA", "label": "Data calcolo busta"},
            {"var": "PAGA_BASE_TOTALE", "label": "Paga base totale"},
            {"var": "TOTALE_INDENNITA", "label": "Totale indennit\u00e0"},
            {"var": "SCATTI_TOTALI", "label": "Scatti totali"},
            {"var": "TOTALE_LORDO", "label": "Totale lordo"},
            {"var": "NETTO_BUSTA", "label": "Netto busta"},
            {"var": "ORE_LAVORATE_MENSILI", "label": "Ore lavorate mensili"},
            {"var": "PAGA_ORARIA_LORDA", "label": "Paga oraria lorda"},
            {"var": "CONTRIBUTI_INPS_TOTALE", "label": "Contributi INPS totale"},
            {"var": "CONTRIBUTI_CASSA_TOTALE", "label": "Contributi cassa totale"},
            {"var": "CONTRIBUTI_CASSA_NOME", "label": "Nome cassa"},
            {"var": "TOTALE_CONTRIBUTI_BUSTA", "label": "Totale contributi busta"},
            {"var": "CONVIVENZA_TOTALE_BUSTA", "label": "Convivenza totale busta"},
            {"var": "TOTALE_ACCANTONATI_BUSTA", "label": "Totale accantonati busta"},
            {"var": "BUDGET_MENSILE_BUSTA", "label": "Budget mensile busta"},
            {"var": "NETTO_MENSILE", "label": "Netto mensile"},
        ],
    },
    {
        "categoria": "CU ANNUALE",
        "items": [
            {"var": "ANNO_CU", "label": "Anno CU"},
            {"var": "REDDITO_LORDO_CU", "label": "Reddito lordo CU"},
            {"var": "CONTRIBUTI_INPS_CU", "label": "Contributi INPS CU"},
            {"var": "CONTRIBUTI_CASSA_CU", "label": "Contributi cassa CU"},
            {"var": "CONTRIBUTI_TOTALI_CU", "label": "Contributi totali CU"},
            {"var": "NETTO_CORRISPOSTO_CU", "label": "Netto corrisposto CU"},
            {"var": "TFR_ACCANTONATO_CU", "label": "TFR accantonato CU"},
            {"var": "INDENNITA_CONVIVENZA_CU", "label": "Indennit\u00e0 convivenza CU"},
            {"var": "IMPONIBILE_FISCALE_CU", "label": "Imponibile fiscale CU"},
            {"var": "MODALITA_CU", "label": "Modalit\u00e0 CU"},
        ],
    },
    {
        "categoria": "FORMATI NUMERICI",
        "items": [
            {"var": "RETRIBUZIONE_TOTALE_NUM", "label": "Retribuzione (numero)"},
            {"var": "CONTRIBUTI_MENSILI_NUM", "label": "Contributi mensili (numero)"},
            {"var": "PAGA_BASE_NUM", "label": "Paga base (numero)"},
            {"var": "PAGA_ORARIA_NUM", "label": "Paga oraria (numero)"},
            {"var": "BUDGET_ANNUALE_NUM", "label": "Budget annuale (numero)"},
            {"var": "BUDGET_MENSILE_NUM", "label": "Budget mensile (numero)"},
            {"var": "ORE_SETTIMANALI_NUM", "label": "Ore settimanali (numero)"},
            {"var": "ORE_MENSILI_NUM", "label": "Ore mensili (numero)"},
            {"var": "ORE_INPS_NUM", "label": "Ore INPS (numero)"},
            {"var": "NETTO_MENSILE_NUM", "label": "Netto mensile (numero)"},
        ],
    },
    {
        "categoria": "FORMATI DATA",
        "items": [
            {"var": "DATA_ODIERNA", "label": "Data odierna (dd/mm/aaaa)"},
            {"var": "DATA_ODIERNA_DB", "label": "Data odierna (aaaa-mm-gg)"},
            {"var": "DATA_ODIERNA_LONG", "label": "Data odierna (esteso)"},
            {"var": "DATA_ODIERNA_COMPLETA", "label": "Data odierna completa"},
            {"var": "GIORNO_CORRENTE", "label": "Giorno del mese"},
            {"var": "GIORNO_SETTIMANA", "label": "Giorno settimana (esteso)"},
            {"var": "GIORNO_SETTIMANA_3", "label": "Giorno settimana (3 let.)"},
            {"var": "NUMERO_SETTIMANA_ISO", "label": "Numero settimana ISO"},
            {"var": "MESE_CORRENTE", "label": "Mese corrente (nome)"},
            {"var": "MESE_CORRENTE_NUMERO", "label": "Mese corrente (numero)"},
            {"var": "MESE_PRECEDENTE", "label": "Mese precedente"},
            {"var": "MESE_SUCCESSIVO", "label": "Mese successivo"},
            {"var": "TRIMESTRE_CORRENTE", "label": "Trimestre corrente"},
            {"var": "ANNO_IN_CORSO", "label": "Anno in corso (4 cifre)"},
            {"var": "ANNO_CORRENTE_2", "label": "Anno in corso (2 cifre)"},
            {"var": "ORA_CORRENTE", "label": "Ora corrente (HH:MM)"},
            {"var": "ORA_CORRENTE_COMPLETA", "label": "Ora corrente (HH:MM:SS)"},
            {"var": "TIMESTAMP_UNIX", "label": "Timestamp Unix"},
        ],
    },
    {
        "categoria": "ENTE / CASSA",
        "items": [
            {"var": "ENTE_BILATERALE", "label": "Ente bilaterale"},
            {"var": "CODICE_ENTE", "label": "Codice ente"},
        ],
    },
    {
        "categoria": "UTENTE",
        "items": [
            {"var": "NOME_UTENTE", "label": "Nome utente"},
            {"var": "COGNOME_UTENTE", "label": "Cognome utente"},
            {"var": "NOME_COGNOME_UTENTE", "label": "Nome e cognome utente"},
            {"var": "EMAIL_UTENTE", "label": "Email utente"},
        ],
    },
    {
        "categoria": "ALTRO",
        "items": [
            {"var": "OPZIONI_ATTIVE", "label": "Opzioni attive"},
            {"var": "INVIO_DIGITALE", "label": "Invio digitale documenti"},
        ],
    },
]
